# 1_10 Dot Product.
- Dot Product or Inner Product or Scalar Product --> Output is an SCALAR.
- CONDITION: vectors must have the same length (one row the other col)
- The outer or tensor product will not be studied.
- CONDITION: matrices must have m x n and n x k --> result: m x k matrix

In [212]:
import numpy as np
np.__version__

'1.26.1'

In [213]:
# Functions

def isndarray(el):
        errmsg = f'- Warning --> {el} is not np.ndarray. It is {type(el)}\n'
        if not isinstance(el, np.ndarray):
                print(errmsg)
                return False
        return True


def show(*objs):
    ''' Display numpy.ndarrays objects and some of its more important attributes

    All arguments must be strings.
    can pass a variable number of non-keyworded arguments.
    '''
    for obj in objs:
        if not isinstance(obj, str):
             print(f'Argument of show() function must be strings."{obj}" is not an String')
             continue

        try:
            robj = eval(obj)
        except NameError:
            robj = obj
        if not isndarray(robj):
                continue

        print(f'{obj} -> {type(robj)}:\n{"-" * 80}')
        print(robj)
        for attr in ('shape', 'ndim', 'size', 'dtype', 'itemsize'):
            obj_attr = obj + '.' + attr
            print(f'{obj_attr} = {eval(obj_attr)}  |  ',end="")
        print('\n')


def dot_prod(v1, v2):
    if not isndarray(v1) or not isndarray(v2):
        return 'dotprod() -> invalid arguments'
    
    ret_val = 0
    for i in range(len(v1)):
        ret_val += v1[i] * v2[i]
    return ret_val



In [214]:
# Vectors definition
vr = np.array([1, 2, 3]).astype('int8')
vc = np.array([9, 8, 7]).reshape(3,1)
show('5', 'casa', 'vr', 'vc', 23, vc)

- Warning --> 5 is not np.ndarray. It is <class 'int'>

- Warning --> casa is not np.ndarray. It is <class 'str'>

vr -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[1 2 3]
vr.shape = (3,)  |  vr.ndim = 1  |  vr.size = 3  |  vr.dtype = int8  |  vr.itemsize = 1  |  

vc -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[9]
 [8]
 [7]]
vc.shape = (3, 1)  |  vc.ndim = 2  |  vc.size = 3  |  vc.dtype = int32  |  vc.itemsize = 4  |  

Argument of show() function must be strings."23" is not an String
Argument of show() function must be strings."[[9]
 [8]
 [7]]" is not an String


In [215]:
# Dot (inner or scalar) product of Vectors
print(1 * 9 + 2 * 8 + 3 * 7)

jmprod = dot_prod(vr, vc)
show('jmprod')

np.dot(vr, vc)

46
jmprod -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[46]
jmprod.shape = (1,)  |  jmprod.ndim = 1  |  jmprod.size = 1  |  jmprod.dtype = int32  |  jmprod.itemsize = 4  |  



array([46])

In [216]:
prod_op = vr * vc
amp_op = vr @ vc
show('prod_op', 'amp_op')

prod_op -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[ 9 18 27]
 [ 8 16 24]
 [ 7 14 21]]
prod_op.shape = (3, 3)  |  prod_op.ndim = 2  |  prod_op.size = 9  |  prod_op.dtype = int32  |  prod_op.itemsize = 4  |  

amp_op -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[46]
amp_op.shape = (1,)  |  amp_op.ndim = 1  |  amp_op.size = 1  |  amp_op.dtype = int32  |  amp_op.itemsize = 4  |  



In [217]:
# Scalars products is a simple multiplication.
ps1 = np.dot([5], [3])
ps2 = np.dot(5, 3)
ps3 = np.dot(5, [3])

show('ps1', 'ps2', 'ps3')


- Warning --> 15 is not np.ndarray. It is <class 'numpy.int32'>

- Warning --> 15 is not np.ndarray. It is <class 'numpy.int32'>

ps3 -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[15]
ps3.shape = (1,)  |  ps3.ndim = 1  |  ps3.size = 1  |  ps3.dtype = int32  |  ps3.itemsize = 4  |  



In [218]:
# Dot product of scalar and vector
np.dot(5, vr)

array([ 5, 10, 15])

In [219]:
5 * vr

array([ 5, 10, 15], dtype=int8)

In [220]:
# Dot product of Matrix and Scalar (only scale the elements)
A = np.array([[2, 8, -4], [0, -3, 6]])
show('A')
np.dot(5, A)

A -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[ 2  8 -4]
 [ 0 -3  6]]
A.shape = (2, 3)  |  A.ndim = 2  |  A.size = 6  |  A.dtype = int32  |  A.itemsize = 4  |  



array([[ 10,  40, -20],
       [  0, -15,  30]])

In [221]:
# Dot product of two matrices
B = np.array([[2, -1], [10, -6], [5, 3]])
show('B')
np.dot(A, B)

B -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[ 2 -1]
 [10 -6]
 [ 5  3]]
B.shape = (3, 2)  |  B.ndim = 2  |  B.size = 6  |  B.dtype = int32  |  B.itemsize = 4  |  



array([[ 64, -62],
       [  0,  36]])

In [222]:
C = np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
C

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [223]:
D = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
D

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [224]:
np.dot(C,D)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])

In [225]:
np.dot([5], vr)

ValueError: shapes (1,) and (3,) not aligned: 1 (dim 0) != 3 (dim 0)

In [ ]:
np.dot(A, A)