# 1_14 Exam.

In [19]:
import numpy as np
np.__version__

'1.26.1'

In [20]:
# Functions

def isndarray(el):
        errmsg = f'- Warning --> {el} is not np.ndarray. It is {type(el)}\n'
        if not isinstance(el, np.ndarray):
                print(errmsg)
                return False
        return True


def show(*objs: str) -> None:
    ''' Display numpy.ndarrays objects and some of its more important attributes

    All arguments must be strings.
    can pass a variable number of non-keyworded arguments.
    Return None, only print info -> FUTURE make an string with all the info as return
    '''
    for obj in objs:
        if not isinstance(obj, str):
             print(f'Argument of show() function must be strings."{obj}" is not an String')
             continue

        try:
            robj = eval(obj)
        except NameError:
            robj = obj
        if not isndarray(robj):
                continue

        print(f'{obj} -> {type(robj)}:\n{"-" * 80}')
        print(robj)
        for attr in ('shape', 'ndim', 'size', 'dtype', 'itemsize'):
            obj_attr = obj + '.' + attr
            print(f'{obj_attr} = {eval(obj_attr)}  |  ',end="")
        print('\n')


def linetot(m1, m2):
    return np.dot(m1, m2)

    
def sumlines(mline):
    sumlt = 0
    for el in mline:
          sumlt += el
    return sumlt
    
     

In [32]:
a = np.array([[[1,2,3], [4,5,6]],[[1,1,1], [2,2,2]]])
b = np.array([[[1,2], [4,5]], [[1,2], [2,2]]])
show('a','b')
a+b

a -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[[1 2 3]
  [4 5 6]]

 [[1 1 1]
  [2 2 2]]]
a.shape = (2, 2, 3)  |  a.ndim = 3  |  a.size = 12  |  a.dtype = int32  |  a.itemsize = 4  |  

b -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[[1 2]
  [4 5]]

 [[1 2]
  [2 2]]]
b.shape = (2, 2, 2)  |  b.ndim = 3  |  b.size = 8  |  b.dtype = int32  |  b.itemsize = 4  |  



ValueError: operands could not be broadcast together with shapes (2,2,3) (2,2,2) 

In [33]:
A = np.array([[5,21,6],[11,8,62]])
B = np.array([[4,5], [6,7], [10,3]])
np.dot(A,B)

array([[206, 190],
       [712, 297]])

In [34]:
z = np.array([2,3])
y = np.array([-2, -3])
np.dot(z,y)

-13

In [35]:
m = np.array([[1,0,-1], [5,4,3]])
n = np.array([[1,0,2], [0,0,2], [1,0,2]])
np.dot(m,n)

array([[ 0,  0,  0],
       [ 8,  0, 24]])

In [38]:
A = n = np.array([[1,1,4], [1,0,2], [4,2,5]])
np.dot(A,A.T)

array([[18,  9, 26],
       [ 9,  5, 14],
       [26, 14, 45]])

In [41]:
v1 = np.array([1,0])
v2 = np.array([0,1])
np.dot(v1,v2)

0

In [40]:
30+18+8

56

## The Case


In [22]:
# Matrices creation
A = np.array([[1,1,1], [1,1,0], [1,1,1], [0,1,1], [1,0,1], [0,1,1], [1,0,0]])
B = np.array([[7.52], [14.83], [12.91]])
show('A', 'B')

A -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[1 1 1]
 [1 1 0]
 [1 1 1]
 [0 1 1]
 [1 0 1]
 [0 1 1]
 [1 0 0]]
A.shape = (7, 3)  |  A.ndim = 2  |  A.size = 21  |  A.dtype = int32  |  A.itemsize = 4  |  

B -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[ 7.52]
 [14.83]
 [12.91]]
B.shape = (3, 1)  |  B.ndim = 2  |  B.size = 3  |  B.dtype = float64  |  B.itemsize = 8  |  



In [23]:
C = np.array([[1,400], [1,695], [1,1046], [1,250], [1,830]])
D = np.array([[10976], [233]])
show('C', 'D')

C -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[   1  400]
 [   1  695]
 [   1 1046]
 [   1  250]
 [   1  830]]
C.shape = (5, 2)  |  C.ndim = 2  |  C.size = 10  |  C.dtype = int32  |  C.itemsize = 4  |  

D -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[10976]
 [  233]]
D.shape = (2, 1)  |  D.ndim = 2  |  D.size = 2  |  D.dtype = int32  |  D.itemsize = 4  |  



In [24]:
np.dot(A, B)

array([[35.26],
       [22.35],
       [35.26],
       [27.74],
       [20.43],
       [27.74],
       [ 7.52]])

In [25]:
np.dot(C, D)

array([[104176],
       [172911],
       [254694],
       [ 69226],
       [204366]])

In [26]:
# Adjusting B for 20% discount on dinner
adjust = np.array([[1,0,0], [0,1,0], [0,0,0.8]])
B_discount = np.dot(adjust, B)
show('adjust', 'B_discount')
#np.dot(B, adjust)   # ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

adjust -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[1.  0.  0. ]
 [0.  1.  0. ]
 [0.  0.  0.8]]
adjust.shape = (3, 3)  |  adjust.ndim = 2  |  adjust.size = 9  |  adjust.dtype = float64  |  adjust.itemsize = 8  |  

B_discount -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[ 7.52 ]
 [14.83 ]
 [10.328]]
B_discount.shape = (3, 1)  |  B_discount.ndim = 2  |  B_discount.size = 3  |  B_discount.dtype = float64  |  B_discount.itemsize = 8  |  



In [27]:
# Without disc suppose 180 - with discount calc - Savings?
daily_spend_disc = np.dot(A, B_discount)

# total_week_discount = 0
# for el in daily_spend_disc:
#     total_week_discount += el
total_week_discount = sumlines(daily_spend_disc)

savings = 180 - total_week_discount

show('daily_spend_disc', 'total_week_discount', 'savings')

daily_spend_disc -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[32.678]
 [22.35 ]
 [32.678]
 [25.158]
 [17.848]
 [25.158]
 [ 7.52 ]]
daily_spend_disc.shape = (7, 1)  |  daily_spend_disc.ndim = 2  |  daily_spend_disc.size = 7  |  daily_spend_disc.dtype = float64  |  daily_spend_disc.itemsize = 8  |  

total_week_discount -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[163.39]
total_week_discount.shape = (1,)  |  total_week_discount.ndim = 1  |  total_week_discount.size = 1  |  total_week_discount.dtype = float64  |  total_week_discount.itemsize = 8  |  

savings -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[16.61]
savings.shape = (1,)  |  savings.ndim = 1  |  savings.size = 1  |  savings.dtype = float64  |  savings.itemsize = 8  |  



In [28]:
# Real total without discount
daily = np.dot(A, B)
week = sumlines(daily)

show('daily', 'week')


daily -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[35.26]
 [22.35]
 [35.26]
 [27.74]
 [20.43]
 [27.74]
 [ 7.52]]
daily.shape = (7, 1)  |  daily.ndim = 2  |  daily.size = 7  |  daily.dtype = float64  |  daily.itemsize = 8  |  

week -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[176.3]
week.shape = (1,)  |  week.ndim = 1  |  week.size = 1  |  week.dtype = float64  |  week.itemsize = 8  |  

