1_5 Scalars, Vectors, Matrices

In [20]:
import numpy as np
np.__version__

'1.26.1'

In [21]:
# Scalar
s = 5
s, type(s)
# s.shape --> AttributeError: 'int' object has no attribute 'shape'

(5, int)

In [22]:
# Scalar as a 0-dim array
s_array = np.array(5)
display(s_array)
display(type(s_array))
display(s_array.shape)
s_array.ndim                # 0-dim array
### - For all practical purpose in Python and within Numpy, integers or floats and array with one element
###     behave in the same way regarding linear algebraic operations.

array(5)

numpy.ndarray

()

0

In [23]:
sa2 = np.array([5])
display(sa2)
display(type(sa2))
display(sa2.shape)
sa2.ndim                # 1-dim array - VECTOR of ONE element

array([5])

numpy.ndarray

(1,)

1

In [24]:
# Vector
v = np.array([5, -2, 4])            # is born as a row vector (¿?) - 1-dim array
v1 = np.array([3.1416, -5/2, 0])
display(v)
display(v1)
display(type(v))
display(v.shape)
v.ndim                              # 1-dim array

array([ 5, -2,  4])

array([ 3.1416, -2.5   ,  0.    ])

numpy.ndarray

(3,)

1

In [25]:
# Reshaping
display(v.shape)
vr = v.reshape(3,1)
display(vr)
vr.shape

(3,)

array([[ 5],
       [-2],
       [ 4]])

(3, 1)

In [26]:
display(v.shape)
vc = v.reshape(1,3)
display(vc)
vc.shape

(3,)

array([[ 5, -2,  4]])

(1, 3)

In [27]:
# Matrix
m = np.array([[5, -2, 9], [12, 0, 3]])
display(m)
display(type(m))
display(m.shape)
m.ndim                                  # 2-dim array


array([[ 5, -2,  9],
       [12,  0,  3]])

numpy.ndarray

(2, 3)

2

In [28]:
# Matrix as vector aggregation
m1 = np.array([v, v1, [12, 0, 3]])
display(m1)
display(type(m1))
display(m1.shape)
m1.ndim                                  # 2-dim array

array([[ 5.    , -2.    ,  4.    ],
       [ 3.1416, -2.5   ,  0.    ],
       [12.    ,  0.    ,  3.    ]])

numpy.ndarray

(3, 3)

2

In [29]:
# 3-dim array 
m3d = np.array([[[1, 2], [3, 4]], [[10, 20], [30, 40]]])
display(m3d)
display(type(m3d))
display(m3d.shape)
m3d.ndim                                  # 3-dim array

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]]])

numpy.ndarray

(2, 2, 2)

3

In [30]:
# 3-dim array as matrices aggregation
m3d1 = np.array([m, m])
display(m3d1)
display(type(m3d1))
display(m3d1.shape)
m3d1.ndim                                  # 3-dim array

array([[[ 5, -2,  9],
        [12,  0,  3]],

       [[ 5, -2,  9],
        [12,  0,  3]]])

numpy.ndarray

(2, 2, 3)

3