# 1_7 Adding and Substractions.
- In order to add (or substract) vectors and matrices, their forms (shapes) must match.

In [39]:
import numpy as np
np.__version__

'1.26.2'

In [40]:
# Functions

def show(*objs):
    for obj in objs:
        print(f'{obj} -> {type(robj:= eval(obj))}:\n{"-" * 50}')
        print(robj)
        print(f'{obj}.shape = {robj.shape}  -  {obj}.ndim = {robj.ndim} dim-array \n')

In [41]:
m1 = np.array([[5,12,6], [-3, 0, 14]])
m2 = np.array([[9,8,7], [1,3,-5]])
show('m1', 'm2')


m1 -> <class 'numpy.ndarray'>:
--------------------------------------------------
[[ 5 12  6]
 [-3  0 14]]
m1.shape = (2, 3)  -  m1.ndim = 2 dim-array 

m2 -> <class 'numpy.ndarray'>:
--------------------------------------------------
[[ 9  8  7]
 [ 1  3 -5]]
m2.shape = (2, 3)  -  m2.ndim = 2 dim-array 



In [42]:
# Addition m1 + m2
sum = m1 + m2
show('sum')

sum -> <class 'numpy.ndarray'>:
--------------------------------------------------
[[14 20 13]
 [-2  3  9]]
sum.shape = (2, 3)  -  sum.ndim = 2 dim-array 



In [43]:
# Subtraction
sub1 = m1 - m2
sub2 = m2 - m1
show('sub1', 'sub2')

sub1 -> <class 'numpy.ndarray'>:
--------------------------------------------------
[[-4  4 -1]
 [-4 -3 19]]
sub1.shape = (2, 3)  -  sub1.ndim = 2 dim-array 

sub2 -> <class 'numpy.ndarray'>:
--------------------------------------------------
[[  4  -4   1]
 [  4   3 -19]]
sub2.shape = (2, 3)  -  sub2.ndim = 2 dim-array 



In [44]:
# Using Vectors
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])
show('v1', 'v2')

v1 -> <class 'numpy.ndarray'>:
--------------------------------------------------
[1 2 3 4 5]
v1.shape = (5,)  -  v1.ndim = 1 dim-array 

v2 -> <class 'numpy.ndarray'>:
--------------------------------------------------
[5 4 3 2 1]
v2.shape = (5,)  -  v2.ndim = 1 dim-array 



In [45]:
sumv = v2 + v1
subva = v2 - v1
subvb = v1 - v2
show('sumv', 'subva', 'subvb')

sumv -> <class 'numpy.ndarray'>:
--------------------------------------------------
[6 6 6 6 6]
sumv.shape = (5,)  -  sumv.ndim = 1 dim-array 

subva -> <class 'numpy.ndarray'>:
--------------------------------------------------
[ 4  2  0 -2 -4]
subva.shape = (5,)  -  subva.ndim = 1 dim-array 

subvb -> <class 'numpy.ndarray'>:
--------------------------------------------------
[-4 -2  0  2  4]
subvb.shape = (5,)  -  subvb.ndim = 1 dim-array 



## 1_8 Errors when adding Matrices

In [46]:
# Adding, subtracting scalars
5 + 5, 10 - 4


(10, 6)

In [47]:
# 'Trying' to add matrices of diff. form
m3 = np.array([[5,12,6], [-3, 0, 14]])
m4 = np.array([[9,8], [1,3]])
show('m3', 'm4')

m3 -> <class 'numpy.ndarray'>:
--------------------------------------------------
[[ 5 12  6]
 [-3  0 14]]
m3.shape = (2, 3)  -  m3.ndim = 2 dim-array 

m4 -> <class 'numpy.ndarray'>:
--------------------------------------------------
[[9 8]
 [1 3]]
m4.shape = (2, 2)  -  m4.ndim = 2 dim-array 



In [48]:
sumb = m3 + m4

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

### NOT valid in Linear Algebra (but no error en py)
- Adding (subs) matrices or vector w/scalars
- Big difference between the concepts of ndarray and tensors.

In [59]:
v3 = np.array([i for i in range(9) if i % 2 != 0])
sumc = m3 + 1
subc = v3 - 1
show('m3', 'v3', 'sumc', 'subc')

m3 -> <class 'numpy.ndarray'>:
--------------------------------------------------
[[ 5 12  6]
 [-3  0 14]]
m3.shape = (2, 3)  -  m3.ndim = 2 dim-array 

v3 -> <class 'numpy.ndarray'>:
--------------------------------------------------
[1 3 5 7]
v3.shape = (4,)  -  v3.ndim = 1 dim-array 

sumc -> <class 'numpy.ndarray'>:
--------------------------------------------------
[[ 6 13  7]
 [-2  1 15]]
sumc.shape = (2, 3)  -  sumc.ndim = 2 dim-array 

subc -> <class 'numpy.ndarray'>:
--------------------------------------------------
[0 2 4 6]
subc.shape = (4,)  -  subc.ndim = 1 dim-array 

