# 1_9 Transposing Vectors and Matrices.
- Transpose a Vector: row vector -> column vector. Or column vector -> row vector. v - vT - vTT = v.
- Transpose a Matrix: each row of m -> each column of mT. Or each column of m -> each row of mT. m - mT - mTT = m. An m x n matrix -transpose-> to n x m matrix.

In [41]:
import numpy as np
np.__version__

'1.26.1'

In [47]:
# Functions

def show(*objs):
    for obj in objs:
        print(f'{obj} -> {type(robj:= eval(obj))}:\n{"-" * 80}')
        print(robj)
        for attr in ('shape', 'ndim', 'size', 'dtype', 'itemsize'):
            obj_attr = obj + '.' + attr
            print(f'{obj_attr} = {eval(obj_attr)}  |  ',end="")
        print('\n')

In [56]:
# Vectors definition
vr = np.array([1, 2, 3]).astype('int8')
vc = np.array([9, 8, 7]).reshape(3,1)
show('vr', 'vc')

vr -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[1 2 3]
vr.shape = (3,)  |  vr.ndim = 1  |  vr.size = 3  |  vr.dtype = int8  |  vr.itemsize = 1  |  

vc -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[9]
 [8]
 [7]]
vc.shape = (3, 1)  |  vc.ndim = 2  |  vc.size = 3  |  vc.dtype = int32  |  vc.itemsize = 4  |  



In [53]:
# Transposing Vectors
vrt = vr.T
vct = vc.T
vctt = vct.T
show('vrt', 'vct', 'vctt')

vrt -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[1 2 3]
vrt.shape = (3,)  |  vrt.ndim = 1  |  vrt.size = 3  |  vrt.dtype = int32  |  vrt.itemsize = 4  |  

vct -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[9 8 7]]
vct.shape = (1, 3)  |  vct.ndim = 2  |  vct.size = 3  |  vct.dtype = int32  |  vct.itemsize = 4  |  

vctt -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[9]
 [8]
 [7]]
vctt.shape = (3, 1)  |  vctt.ndim = 2  |  vctt.size = 3  |  vctt.dtype = int32  |  vctt.itemsize = 4  |  



In [57]:
# Transposing Matrices
m = np.array([[1, 2, 3], [9, 8, 7]]).astype('int8')
mt = m.T
mtt = mt.T
show('m', 'mt', 'mtt')

m -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[1 2 3]
 [9 8 7]]
m.shape = (2, 3)  |  m.ndim = 2  |  m.size = 6  |  m.dtype = int8  |  m.itemsize = 1  |  

mt -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[1 9]
 [2 8]
 [3 7]]
mt.shape = (3, 2)  |  mt.ndim = 2  |  mt.size = 6  |  mt.dtype = int8  |  mt.itemsize = 1  |  

mtt -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[[1 2 3]
 [9 8 7]]
mtt.shape = (2, 3)  |  mtt.ndim = 2  |  mtt.size = 6  |  mtt.dtype = int8  |  mtt.itemsize = 1  |  



In [59]:
# Others Matrices examples
m2x2 = np.array([[5, 4], [-2, 0]])
m2x2

array([[ 5,  4],
       [-2,  0]])

In [60]:
m2x2.T

array([[ 5, -2],
       [ 4,  0]])

In [61]:
m2x4 = np.array([[14, 0, 9, 6], [1, 3, 5, 7]])
m2x4

array([[14,  0,  9,  6],
       [ 1,  3,  5,  7]])

In [62]:
m2x4.T

array([[14,  1],
       [ 0,  3],
       [ 9,  5],
       [ 6,  7]])

In [63]:
# Transposing scalars --> NOTHING!
s = np.array([5])
s1 = np.array(5)
st = s.T
s1t = s1.T
show('s', 's1', 'st', 's1t')

s -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[5]
s.shape = (1,)  |  s.ndim = 1  |  s.size = 1  |  s.dtype = int32  |  s.itemsize = 4  |  

s1 -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
5
s1.shape = ()  |  s1.ndim = 0  |  s1.size = 1  |  s1.dtype = int32  |  s1.itemsize = 4  |  

st -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
[5]
st.shape = (1,)  |  st.ndim = 1  |  st.size = 1  |  st.dtype = int32  |  st.itemsize = 4  |  

s1t -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------
5
s1t.shape = ()  |  s1t.ndim = 0  |  s1t.size = 1  |  s1t.dtype = int32  |  s1t.itemsize = 4  |  

