# 7. Data Preprocessing with NumPy

## Course Summary
- Complete List of Functions and Methods learned.
- List of Functions and Methods by section.
- Some clear examples by section
- Extra jm-tries.

## Complete List of Functions and Methods learned.

### 4. Working with Array
1. __numpy.squeeze(a, axis=None)__
   - Remove axes of length one from a.
2. __ndarray.squeeze(axis=None)__
   - Remove axes of length one from a.

### 5. Generating Data with NumPy
1. __numpy.empyt(shape=, dtype=)__
   - .ones(); .zeros(), .full(fill_value)
2. __ndarray.empy_like(arr, dtype=)__
   - ones_like(); zeros_like(), full_like(fill)
3. __ Generator
   - PCG64 bit generator | rg = gen(pcg(seed=42)); rg.normal(size=(3,5)) 

### 8. Data Manipulation with NumPy
1. __np.loadtxt('filenm', delimiter=, dtype=, usecols=)__
   - fails with missing vals (NANs)
2. __np.isnan(arr)__ {ufunc}
   - np.isnan().sum()
3. __np.genfromtxt('filenm', delimiter=, filling_values=tmp)__
    - dtype=float, usecols=None, skip_header or footer=0
4. __np.where(condition, True, False)__
5. __np.reshape()__ <- inplace Flase>
    - add dims artificially -> np.reshape(1,1,3,5) + method
6. __np.delete(arr, ixs, axis=None)__ <- inplace False>
    - 2-D arr axis=0 row, axis=1 cols | .delete(.delete( axis=1) axis=0) cols and rows
7. __np.sort(arr, axis=1)__ <- inplace False>
    - -np.sort(-arr) <- descending | arr.sort() <- inplace True!! | axis=-1 default (en 2D is = 1 rows)
8. __np.argsort(arr, axis=-1)__ <- inplace False>
    - .argsort() method idem <- inplacer False>
9.  __np.argwhere(arr)__ {arr or condition}
    - indices of non-zero elements of arr | argwhere(isnan(a))
10.  __np.shuffle(arr)__ <-inplace True> NO axis= (only rows)
     - Also .shuffle(arr, axis=0) Generator method <-inplace True> | 2-D array axis=0 shuffle rows, axis=1 shuffle cols.
11. np.astype() | <- inplace False> idem the .astype() method
12. np.chararray.strip(arr, 'str') <- inplacer False>
13. np.stack(arr, axis=0) <- inplace False>
    - stack add 1Dim | .stack() SAME shape, .vstack() and .hstack() NO  | .dstack() depth
14. __np.concatenate((tup_arrs), axis=0)__ <-inplace False>
    - axis=0 > .vstack; axis=1 > .hstack; axis=2 > dstack
15. __np.unique(arr, return_index=False, return_counts=False)__
    - return unique values, ascending sorted

### 0. Import Libraries, set np print options, and Functions

In [39]:
import numpy as np
np.__version__
# np.set_printoptions(suppress=True, linewidth=100, precision=2)

'1.26.4'

In [40]:
# Function show_attr

def show_attr(arrnm: str) -> str:
    strout = f' {arrnm}: '

    for attr in ('shape', 'ndim', 'size', 'dtype'):     #, 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

### 1. Introduction to NumPy

- 1/2. NumPy arrays allow for element-wise operations, leading to more efficient computations.
- 2/2. NumPy is suitable for data analysis because it is not only stable but also offers shorter computation times due to its low-level language roots. > True <

- 1/2. A 0-dimensional array is equivalent to a scalar value. | A 1-dimensional array can be thought of as a vector. | A 2-dimensional array in NumPy is similar to a matrix in linear algebra.
- 2/2. A scalar is a single data point in NumPy, also known as a 0D array.
    - A vector is a sequence of values, representing a 1D array.
    - A 2D array in NumPy is equivalent to a matrix, consisting of rows and columns.

- 1/1. Press Shift + Tab after typing the function name -> check doc in Jupyter

### 2. Why do we use NumPy

- 1/1. Why was NumPy created?: There was a need for a unified array type.

- 1/2. Lists concatenate elements, while arrays perform element-wise addition.
- /2. NumPy arrays have a .shape attribute, while Python lists do not <> True <>

### 3. NumPy Fundamentals

- 1/4 - element Indexing

In [41]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_a[1, 2]                              # jm -> 6 np.int

6

- 2/4. Negative indices in NumPy will result in IndexOutOfBounds error. <> FALSE <>
- 3/4. In NumPy, indexing starts at 0 for both rows and columns.
    - To retrieve an entire column in a 2D array, use a colon (:) in place of the row index. 
-4/4. NumPy uses zero-based indexing.
    - NumPy allows negative indices.
    - The shape of an array affects the number of indices you need to provide.

- 1/2. dtype Numeric ex. np.int32, np.float64 - Non-numeric: np.str, np.bool
- 2/2. If an array is created in NumPy without explicitly specifying the data type, NumPy automatically assigns the smallest possible data type that can store the values in the array.

- 1/3. Elementwise multiplication between two NumPy arrays always requires the arrays to have the same dimensions. <> FALSE <>
- 2/3. TypeCasting - dtype
- 3/3. In NumPy, typecasting is performed only on the output of an operation (e.g. np.add()), not the inputs themselves. <> FALSE <>

## 4. Working with Arrays

- 3/8. In stepwise slicing, using a step of 0 will result in an error because it means no movement within the array.
- 4/8. Conditional slicing in NumPy returns a one-dimensional array, even if the original array is multi-dimensional
- 6/8. Either greater than 4 or are even? C[(C > 4) | (C % 2 == 0)]
- 8/8. The NumPy squeeze() function removes all dimensions of size 1 from an array.

## 5. Generating Data with NumPy

## 6. Importing and Saving Data with Numpy

## 7. Statistics with NumPy

### 8. Data Manipulation with NumPy

## Xtra jm-tries 

In [42]:
# Basic slicing
display(A := np.arange(15).reshape(3,5))
display(A[1:, 1:4])
display(A[2:, 3:])
display(A[0])
display(A[:,0])
display(A[0:1])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[ 6,  7,  8],
       [11, 12, 13]])

array([[13, 14]])

array([0, 1, 2, 3, 4])

array([ 0,  5, 10])

array([[0, 1, 2, 3, 4]])

In [43]:
# Stepwise slicing
A[::-1, -1::-3]

array([[14, 11],
       [ 9,  6],
       [ 4,  1]])

In [44]:
# Conditional slicing or bool indexing - Out 1D array
display(A)
display(A[(A % 2 != 0) & (A <= 9)])

display(b_arr := np.zeros_like(A, dtype=bool))
# b_arr[[0,1,2,1,0], [0,1,2,3,4]] = True
b_arr[(0,1,2,1,0), [range(5)]] = True
# b_arr[(0,1,2,1,0), (0,1,2,3,4)] = True
display(b_arr)

display(A[b_arr])    # Barre por filas 

b_arr[:] = True
display(A[b_arr])
display(A[True])
A[False]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([1, 3, 5, 7, 9])

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

array([[ True, False, False, False,  True],
       [False,  True, False,  True, False],
       [False, False,  True, False, False]])

array([ 0,  4,  6,  8, 12])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

array([], shape=(0, 3, 5), dtype=int32)

In [45]:
# ndarray.squezze() - np.squeeze()
display(A[0,0])
print(type(A[0,0]))
print(show_attr('A[0,0]'))

display(A[0:1,0:1])
print(type(A[0:1,0:1]))
print(show_attr('A[0:1,0:1]'))

display(A[0:1,0:1].squeeze())
print(type(A[0:1,0:1].squeeze()))
print(show_attr('A[0:1,0:1].squeeze()'))

0

<class 'numpy.int32'>
 A[0,0]: | shape: () | ndim: 0 | size: 1 | dtype: int32 


array([[0]])

<class 'numpy.ndarray'>
 A[0:1,0:1]: | shape: (1, 1) | ndim: 2 | size: 1 | dtype: int32 


array(0)

<class 'numpy.ndarray'>
 A[0:1,0:1].squeeze(): | shape: () | ndim: 0 | size: 1 | dtype: int32 
