# 7. Data Preprocessing with NumPy
- Practice Exam #1
- Practice Exam #2
- Practice Exam #3
- Practice Exam #4

## PE#1 - Indexing, Assigning, np.squeeze()

1. __np.loadtxt('filenm', delimiter=, dtype=, usecols=)__
   - fails with missing vals (NANs)
2. __np.isnan(arr)__ {ufunc}
   - np.isnan().sum()
3. __np.genfromtxt('filenm', delimiter=, filling_values=tmp)__
    - dtype=float, usecols=None, skip_header or footer=0
4. __np.where(condition, True, False)__
5. __np.reshape()__ <- inplace Flase>
    - add dims artificially -> np.reshape(1,1,3,5) + method
6. __np.delete(arr, ixs, axis=None)__ <- inplace False>
    - 2-D arr axis=0 row, axis=1 cols | .delete(.delete( axis=1) axis=0) cols and rows
7. __np.sort(arr, axis=1)__ <- inplace False>
    - -np.sort(-arr) <- descending | arr.sort() <- inplace True!! | axis=-1 default (en 2D is = 1 rows)
8. __np.argsort(arr, axis=-1)__ <- inplace False>
    - .argsort() method idem <- inplacer False>
9.  __np.argwhere(arr)__ {arr or condition}
    - indices of non-zero elements of arr | argwhere(isnan(a))
10.  __np.shuffle(arr)__ <-inplace True> NO axis= (only rows)
     - Also .shuffle(arr, axis=0) Generator method <-inplace True> | 2-D array axis=0 shuffle rows, axis=1 shuffle cols.
11. np.astype() | <- inplace False> idem the .astype() method
12. np.chararray.strip(arr, 'str') <- inplacer False>
13. np.stack(arr, axis=0) <- inplace False>
    - stack add 1Dim | .stack() SAME shape, .vstack() and .hstack() NO  | .dstack() depth
14. __np.concatenate((tup_arrs), axis=0)__ <-inplace False>
    - axis=0 > .vstack; axis=1 > .hstack; axis=2 > dstack
15. __np.unique(arr, return_index=False, return_counts=False)__
    - return unique values, ascending sorted


In [1]:
import numpy as np
np.__version__
np.set_printoptions(suppress=True)

In [2]:
# Function show_attr

def show_attr(arrnm: str) -> str:
    strout = f' {arrnm}: '

    for attr in ('shape', 'ndim', 'size', 'dtype'):     #, 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

In [3]:
# load NON-NAN data
dataU = np.loadtxt('Lending-Company-Numeric-Data.csv',
                  delimiter=',')
print(show_attr('dataU'))
np.isnan(dataU).sum()

 dataU: | shape: (1043, 6) | ndim: 2 | size: 6258 | dtype: float64 


0

In [4]:
# read NAN data
dataN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                     delimiter=';')
print(show_attr('dataN'))
np.isnan(dataN).sum()

 dataN: | shape: (1043, 6) | ndim: 2 | size: 6258 | dtype: float64 


260

In [10]:
# read exam data 
data = np.genfromtxt('Data_preprocessing_Numpy.csv',
                     delimiter=';')
                    #  skip_header=1)

display(data)
print(show_attr('data'))
print(np.isnan(data).sum())


array([[   nan,    nan,    nan,    nan,    nan,    nan],
       [   nan,    50.,   365.,  2801.,  3626.,  4676.],
       [   nan,    40.,   365.,  3121.,  5381., 15281.],
       [   nan,    40.,   365.,  3121.,  4501., 16381.],
       [   nan,    50.,   365.,  1700.,  3200., 16550.],
       [   nan,    40.,   365.,  3401.,  4421., 13101.],
       [   nan,    50.,   365., -1850.,  -530.,  1480.],
       [   nan,    50.,   365.,  3750.,  6250., 20250.],
       [   nan,    50.,   365.,  3751.,  5251., 20250.],
       [   nan,    nan,    nan,  5453.,  6953., 22250.],
       [   nan,    nan,    nan,  5100.,  6400., 22250.],
       [   nan,    40.,   365.,  3400.,  5400., 16600.],
       [   nan,    40.,   365.,  3360.,    nan,    nan],
       [   nan,    40.,   365.,  1940.,    nan,    nan],
       [   nan,    50.,   365.,  5500.,  7500., 22250.],
       [   nan,    nan,    nan,    nan,    nan,    nan],
       [   nan,    50.,   365.,  1250.,  2650., 19250.],
       [   nan,    50.,   365.,

 data: | shape: (31, 6) | ndim: 2 | size: 186 | dtype: float64 
61


In [6]:
# Q1

In [14]:
# Q2
np.nanmean(data, axis=0).round(2)

C:\Users\jm\AppData\Local\Temp\ipykernel_1480\1500593355.py:2: RuntimeWarning: Mean of empty slice
  np.nanmean(data, axis=0).round(2)


array([     nan,    47.5 ,   365.  ,  3495.16,  5073.5 , 18461.31])

In [21]:
# Q3
# print('1stColMean:', np.nanmean(data[:,0]))
# print('2ndColMean:', np.nanmean(data[:,1]))
# print('3thColMean:', np.nanmean(data[:,2]))
# print('4thColMean:', np.nanmean(data[:,3]))

display(mini := np.nanmin(data))
Nixs = np.argwhere(np.isnan(data))
for ni in Nixs:
    data[ni[0], ni[1]] = mini
data
np.mean(data, axis=0).round(2)

-1850.0

array([-1850.  ,  -258.55,  -135.16,  2460.61,  3510.13, 15185.29])

In [35]:
# Q4
A = np.array([[12,34,-15,56], [23,22,90,-56], [4,-19,27,31], [45,56,61,70]])
display(np.sort(A, axis=None))
display(np.sort(np.reshape(A, (16,))))
#                     np.sort(A).reshape(16,)     # BAD
# A.sort(axis=None)
# A

array([-56, -19, -15,   4,  12,  22,  23,  27,  31,  34,  45,  56,  56,
        61,  70,  90])

array([-56, -19, -15,   4,  12,  22,  23,  27,  31,  34,  45,  56,  56,
        61,  70,  90])

TypeError: 'NoneType' object cannot be interpreted as an integer

In [ ]:
# Q5
for null_pos in np.argwhere(np.isnan(data)):
    # dataN[null_pos[0], null_pos[1]] = 1
    pass

np.isnan(dataN).sum()

In [31]:
# Q6
d = np.array([['e_1', 'e_4', 'e_2', 'e_3'], [1,2,2,3]])
d
display(d[0,:])
display(np.stack((d[0],d[1]), axis=1))
np.dstack((d[0],d[1]))
# d[0,:] = np.chararray.strip(data[0,:], 'e_')
# r_d = np.array((d[0,:],))

array(['e_1', 'e_4', 'e_2', 'e_3'], dtype='<U11')

array([['e_1', '1'],
       ['e_4', '2'],
       ['e_2', '2'],
       ['e_3', '3']], dtype='<U11')

array([[['e_1', '1'],
        ['e_4', '2'],
        ['e_2', '2'],
        ['e_3', '3']]], dtype='<U11')

## Some Questions - Exercises 

In [ ]:
# Q1 
dataN0 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                       delimiter=';',
                       skip_header=1)
np.isnan(dataN0).sum()

In [ ]:
# Q3 Change NAN to min
# display(c1_min := np.nanmin(dataN[:,0]))      # 1000.0
display(c1b_min := np.nanmin(dataN[0:,:1]))
print(np.isnan(dataN[0:,:1]).sum())
# Imposible change NANs without indices
for val in dataN[0:,:1]:
    # if val == [np.nan]:
    if np.isnan(val):
        pass
        # print(val)
        # print(val, end=' - ')

In [ ]:
# Q3 2nd col (col[1]) dataN mean -258.55
print('1stColMean:', np.nanmean(dataN[:,0]))
print('2ndColMean:', np.nanmean(dataN[:,1]))
print('3thColMean:', np.nanmean(dataN[:,2]))
print('4thColMean:', np.nanmean(dataN[:,3]))

In [ ]:
# Q4 Sort a flattened version of the array - diff. alternatives
A = np.array([[12,34,-15,56], [23,22,90,-56], [4,-19,27,31], [45,56,61,70]])
display(np.sort(A, axis=None))
display(np.sort(np.reshape(A, (16,))))
#                     np.sort(A).reshape(16,)     # BAD

In [ ]:
# Q5 Replace NANs with 1 - ELIMINATE NANs from 'dataN'
for null_pos in np.argwhere(np.isnan(dataN)):
    # dataN[null_pos[0], null_pos[1]] = 1
    pass

np.isnan(dataN).sum()

### 1. When using the np.sum() function on a boolean array returned by np.isnan(), the result will indicate the total number of missing values in the dataset.
- True
- Explanation: In NumPy, True can be represented with 1 and False can be represented with 0. Summing the boolean array returned by np.isnan() will count the number of True values, which corresponds to the number of missing values.

### 2. Filling missing values with the mean of the column will not change the overall mean of that column.
- True
- Explanation: Filling missing values with the mean of a column ensures that the overall mean remains unchanged. This method keeps the distribution of data consistent while handling missing values.

### 3. What does the np.where() function do?
- It replaces values in an array based on a condition.

### 4. Setting axis=None in np.sort() on a 2D array will sort the flattened array and return a 1D array.
- True 

### 5. Which of the following best describes the default behavior of np.sort() when sorting a 2D array?
- It sorts each row of the array in ascending order.
- Explanation: The default behavior of np.sort() on a 2D array is to sort each row (the last axis) individually in ascending order.

### 6. The np.argwhere() function returns the coordinates of all non-zero elements in a NumPy array by
- True
- Explanation: By default, np.argwhere() checks for non-zero elements in the array and returns their coordinates as indices in a 2D array.

### 7. When using np.random.shuffle() the function returns a new array without modifying the original array.
- False
- Explanation: np.random.shuffle() modifies the array in place, meaning it rearranges the rows of the dataset directly and does not return a new array.

### 8. You have a 2D array of float values and you want to cast them into integers. Complete the following code:


In [ ]:
data = np.array([[1.2, 2.5, 3.1], [4.6, 5.8, 6.9]]) 

# Convert float values to integers
int_data = data.astype(dtype = np.int32) 
print(int_data)

## Some JM - Exercises

In [ ]:
# 5. reshape function and method
display(A := np.arange(1,7).reshape(2,3))
np.reshape(A, (3,2))    # <- Inplace=False
display(A)
A.reshape(3,2)          # <- Inplace=False
B = A.reshape(3,2) 
B

In [ ]:
# 7. sort function and method
display(C := np.arange(6,0,-1).reshape(2,3))
display(np.sort(C))
display(np.sort(C, axis=1))
display(np.sort(C, axis=-1))    # sort rows
C
display(np.sort(C, axis=0))     # sort cols
C
display(C.sort())
C

In [ ]:
# sorting in descending order
display(np.flip(np.sort(C)))
display(C)
-np.sort(-C)
C

In [ ]:
# Sorting letters in descending order
lst = [chr(i) for i in range(100, 115)]
display(L := np.array(lst).reshape(3,5))
display(np.sort(L))
np.flip(np.sort(L))
# numpy.flip(m, axis=None)

In [ ]:
# True - False element-wise letters
display(L)
L[0,3] = '' 
L[1,1] = 0
L[2,4] = False
display(L)
display(L[L == True])
display(L[L == False])
display(L[L != False])

In [ ]:
# True - False element-wise nums
display(R := np.random.randn(15).round(2).reshape(3,5) * 17)
R[0,3] = R[1,0] = R[2,4] = 0
display(R)
display(R[R == True])
display(R[R == False])
display(R[R != False])
display(R[R != True])

In [ ]:
# 10 .shuffle Gen method, inplace True, axis=0 rows default
display(I := np.arange(18).reshape(3,6))

from numpy.random import Generator as gen  
from numpy.random import PCG64 as pcg 

array_RG = gen(pcg())
array_RG.shuffle(I, axis=0)

I


In [20]:
# display(I := np.arange(18).reshape(3,6))
# np.random.shuffle(I, axis=1)
# I
# # TypeError: shuffle() got an unexpected keyword argument 'axis'

In [ ]:
# 11 .astype() method <- inplace False
display(I := np.arange(18).reshape(3,6))
display(I)
display(I.astype(dtype=str))
display(I)

In [ ]:
## 13. The truth about the 'same' shape in stacks
display(S := np.arange(24).reshape(4,6))
display(S2r := S[[-1,-2]])
# np.stack((S,S2r)) # ValueError: all input arrays must have the same shape
# np.stack((S, S2r), axis=1)    # ValueError:

np.vstack((S,S2r))  # OK!!

In [ ]:
## 14. Concatenate - v-h stack <- dimensions
display(S := np.arange(24).reshape(4,6))
print(show_attr('S'))
display(S2r := S[[-1,-2]])
print(show_attr('S2r'))
display(S2c := S[:,[2,1]])
print(show_attr('S2c'))

display(concat_r := np.concatenate((S, S2r)))
print(show_attr('concat_r'))

display(vstack := np.vstack((S, S2r)))
print(show_attr('vstack'))

display(stack_r := np.stack((S, S)))
print(show_attr('stack_r'))

display(concat_c := np.concatenate((S, S2c), axis=1))
print(show_attr('concat_c'))

display(hstack := np.hstack((S, S2c)))
print(show_attr('hstack'))

display(stack_c := np.stack((S, S), axis=1))
print(show_attr('stack_c'))