# 7. Data Preprocessing with NumPy
## Maths Final Exam Practice

## 0. Load Libraries and def. Functions

In [1]:
import numpy as np
from numpy.random import Generator as gen  
from numpy.random import PCG64 as pcg   

np.__version__
np.set_printoptions(suppress=True, linewidth=100, precision=2)

In [2]:
# Function show_attr def

def show_attr(arrnm: str) -> str:
    ''' Show numpy ndarray principal attributes
    
    arrnm: array name. Must exist en the main program body
    --> CAN NOT be call inside other function
    '''
    
    if not isinstance(arrnm, str):
          return '-> show_attr() >> ERROR: argument must be an string!'
    
    strout = f' {arrnm}: '
    for attr in ('shape', 'ndim', 'size', 'dtype'):     #, 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

## Case 1/4

In [3]:
# 1. 0D scalar, 1D Vector, 2D Matrices (Tensors rank 0,1,2 - then 3,4,...)
cero = np.array(1)
# cero = [1] - In Math OD
vector = np.array([1,2,3])
display(show_attr('cero'), show_attr('vector'))

' cero: | shape: () | ndim: 0 | size: 1 | dtype: int32 '

' vector: | shape: (3,) | ndim: 1 | size: 3 | dtype: int32 '

In [4]:
# 2. In Math can´t add matrices of diff shape. (In np broadcasting)

In [5]:
# 3. arr.shape -> (num_rows, num_cols)
m = np.array([[19,12,2], [1,0,5]])
m.T

array([[19,  1],
       [12,  0],
       [ 2,  5]])

In [6]:
# 4. Add and Subtraction of matrices SAME SHAPE in Math (np broadcasting) 


In [7]:
# 5. Inner Product - np.dot()
A = np.array([[5,21,6], [11,8,62]])
B = np.array([[4,5], [6,7], [10,3]])
display(np.dot(A,B))
np.dot(B,A)

array([[206, 190],
       [712, 297]])

array([[ 75, 124, 334],
       [107, 182, 470],
       [ 83, 234, 246]])

In [8]:
# 6. np.dot(A,B) != np.dot(B,A)

## Case 2/4

1. __numpy.empyt(shape=, dtype=)__

In [9]:
# 7. Scalars 0D - Vectors 1D - Matrices 2D

In [10]:
# 8. Vector v of length > 1
# - Length = number of elements in the vector
# - Length is the number of elements after being transposed

In [11]:
# 9. .dot() and graphical
a = np.array([2,3])
b = np.array([-2,-3])
np.dot(a,b)
# NOT orthogonal vectors
# NOT reflection respect y=-x

-13

In [12]:
# 10. v.shape (num_rows, num_cols)

In [13]:
# 11. Indexing and Operating

# find a_1-b_1

In [14]:
# 12. Adding matrices inside tensors

## Case 3/4

In [15]:
# 13. .dot() 

In [16]:
# 14. .dot() a transp
display(A := np.array([[1,1,4], [1,0,2], [4,2,5]]))
display(A.T)
display(np.dot(A,A.T))    # Inner Product
# display(A * A)          # Elemwise Product

array([[1, 1, 4],
       [1, 0, 2],
       [4, 2, 5]])

array([[1, 1, 4],
       [1, 0, 2],
       [4, 2, 5]])

array([[18,  9, 26],
       [ 9,  5, 14],
       [26, 14, 45]])

In [17]:
# 15. .dot(N,M) + 5 * P
# To de addition SAME SHAPE!!

In [18]:
# 16. 3 * c1 + 2 * c2 + c3

In [19]:
# 17. Orthogonal vector dot or inner prod is 0
a = np.array([0,1])
b = np.array([1,0])
np.dot(b,a)

0

In [20]:
# # 18. Prod and Subtraction
# R = scalar? * A - B

## Case 4/4

In [22]:
# 19. Matrix for record triathlon training data (swim, run, cycle) for all week.
td = np.zeros(shape=(7,3))
# td

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# 20. Calculate the total performance for e/day of train. (Two days case)
display(two_days := np.array([[15.4, 30, 27.3], [14.5, 32.25, 29]]))
tot_by_day = np.dot(tot_by_day, [1,1,1])
tot_by_day

array([[15.4 , 30.  , 27.3 ],
       [14.5 , 32.25, 29.  ]])

array([72.7 , 75.75])

In [38]:
# 20. JM Inner Prod (.dot) MANUAL
display(w := np.ones(shape=3, dtype=np.int8))
display(result := np.zeros(shape=(two_days.shape[0])))

for r in range(two_days.shape[0]):
    val = 0
    for c in range(two_days.shape[1]):
        val += two_days[r,c] * w[r]
    result[r] = val

result

array([1, 1, 1], dtype=int8)

array([0., 0.])

array([72.7 , 75.75])

In [40]:
# 21. What is the diff between them
display(diff := result[1] - result[0])

3.049999999999997

In [ ]:
# 22. Best time in training (two_days[0]) worse than previous cmpt. result.
# 22. swim (two_days[0,0]) and cycle (two_days[0,2]) 10% less
# 22. run (  ) 2% less

In [ ]:
# 23. Total time of competition.

In [ ]:
# 24. 