# 7. Data Preprocessing with NumPy
## Maths Final Exam Practice

## 0. Load Libraries and def. Functions

In [25]:
import numpy as np
from numpy.random import Generator as gen  
from numpy.random import PCG64 as pcg   

np.__version__
np.set_printoptions(suppress=True, linewidth=100, precision=2)

In [26]:
# Function show_attr def

def show_attr(arrnm: str) -> str:
    ''' Show numpy ndarray principal attributes
    
    arrnm: array name. Must exist en the main program body
    --> CAN NOT be call inside other function
    '''
    
    if not isinstance(arrnm, str):
          return '-> show_attr() >> ERROR: argument must be an string!'
    
    strout = f' {arrnm}: '
    for attr in ('shape', 'ndim', 'size', 'dtype'):     #, 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

## Case 1/4

In [27]:
# 1. 0D scalar, 1D Vector, 2D Matrices (Tensors rank 0,1,2 - then 3,4,...)
cero = np.array(1)
# cero = [1] - In Math OD
vector = np.array([1,2,3])
display(show_attr('cero'), show_attr('vector'))

' cero: | shape: () | ndim: 0 | size: 1 | dtype: int32 '

' vector: | shape: (3,) | ndim: 1 | size: 3 | dtype: int32 '

In [28]:
# 2. In Math can´t add matrices of diff shape. (In np broadcasting)

In [29]:
# 3. arr.shape -> (num_rows, num_cols)
m = np.array([[19,12,2], [1,0,5]])
m.T

array([[19,  1],
       [12,  0],
       [ 2,  5]])

In [30]:
# 4. Add and Subtraction of matrices SAME SHAPE in Math (np broadcasting) 


In [50]:
# 5. Inner Product - np.dot()
A = np.array([[5,21,6], [11,8,62]])
B = np.array([[4,5], [6,7], [10,3]])
display(np.dot(A,B))
np.dot(B,A)

array([[206, 190],
       [712, 297]])

array([[ 75, 124, 334],
       [107, 182, 470],
       [ 83, 234, 246]])

In [ ]:
# 6. np.dot(A,B) != np.dot(B,A)

## Case 2/4

1. __numpy.empyt(shape=, dtype=)__

In [ ]:
# 7. Scalars 0D - Vectors 1D - Matrices 2D

In [ ]:
# 8. Vector v of length > 1
# - Length = number of elements in the vector
# - Length is the number of elements after being transposed

In [51]:
# 9. .dot() and graphical
a = np.array([2,3])
b = np.array([-2,-3])
np.dot(a,b)
# NOT orthogonal vectors
# NOT reflection respect y=-x

-13

In [ ]:
# 10. v.shape (num_rows, num_cols)

In [ ]:
# 11. Indexing and Operating

# find a_1-b_1

In [ ]:
# 12. Adding matrices inside tensors

## Case 3/4

In [ ]:
# 13. .dot() 

In [54]:
# 14. .dot() a transp
display(A := np.array([[1,1,4], [1,0,2], [4,2,5]]))
display(A.T)
display(np.dot(A,A.T))    # Inner Product
# display(A * A)          # Elemwise Product

array([[1, 1, 4],
       [1, 0, 2],
       [4, 2, 5]])

array([[1, 1, 4],
       [1, 0, 2],
       [4, 2, 5]])

array([[18,  9, 26],
       [ 9,  5, 14],
       [26, 14, 45]])

array([[ 1,  1, 16],
       [ 1,  0,  4],
       [16,  4, 25]])

In [ ]:
# 15. .dot(N,M) + 5 * P
# To de addition SAME SHAPE!!

In [ ]:
# 16. 3 * c1 + 2 * c2 + c3

In [56]:
# 17. Orthogonal vector dot or inner prod is 0
a = np.array([0,1])
b = np.array([1,0])
np.dot(b,a)

0

In [57]:
# # 18. Prod and Subtraction
# R = scalar? * A - B

Object `scalar` not found.


## Case 4/4