# Appendix 1 - Functions
- https://docs.python.org/3/library/string.html#format-specification-mini-language
- https://realpython.com/python-f-strings/

[## 0. Import Libraries](#0-import-libraries)    
[## 1. show_attr function](#1-show_attr-function)    
[## 2. show_thsep function](#2-show_thsep-function)    
[## 3. show_tharrsep function](#3-show_tharrsep-function)

## 0. Import Libraries

In [1]:
import numpy as np
np.__version__
np.set_printoptions(suppress=True, linewidth=100)
# np.set_printoptions(suppress=True, linewidth=100, precision=2)

import numpy

In [2]:
# Create some test arrays
int_arange = np.arange(15).reshape(3,5)
float_rand = np.round(np.random.random(size=(3,5)) * 500_000, 2)
int_rand = np.random.randint(10, 40, size=(3,5))
float_arange = np.arange(10000, 10045, 3, dtype=np.float32).reshape(3,5)

arr_1D = float_rand[1]
arr_3D = np.array([float_arange, float_rand])

# display(int_arange, float_rand, int_rand, float_arange, arr_1D, arr_3D)


## 1. show_attr function

[# Appendix 1 - Functions](#appendix-1---functions)

In [3]:
# Function show_attr def

def show_attr(arrnm: str) -> str:
    ''' Show numpy ndarray principal attributes
    
    arrnm: array name. Must exist en the main program body
    --> CAN NOT be call inside other function
    '''
    
    if not isinstance(arrnm, str):
          return '-> show_attr() >> ERROR: argument must be an string!'
    
    strout = f' {arrnm}: '
    for attr in ('shape', 'ndim', 'size', 'dtype'):     #, 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

In [4]:
# show_attr test
display(show_attr('int_rand'))
# display(show_attr(int_rand))    # '--> show_attr() >> ERROR: argument must be an string!'
# show_attr?

' int_rand: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 '

In [5]:
# Shapes and attributes
# display(arr_1D, show_attr('arr_1D'))
# display(arr_1D)
# arr_1D = np.reshape(arr_1D, (5,1))
# display(arr_1D, show_attr('arr_1D'))

## 2. show_thsep function

[# Appendix 1 - Functions](#appendix-1---functions)

In [6]:
# Function show_thsep

def show_thsep(num: float, sep: str = ',') -> str:
    '''Show a number as str with thousands separator
    
    num: a real number (int or float)
    sep: separator, valid are: ','or '_'.
    '''
    try:
        out = f'{num:{sep}}'
    except ValueError as ve:
        return f'-> show_thsep() > ValueError({ve})'
    except TypeError as te:
        msg = '-> show_thsep() > TypeError: '
        msg += f'argument must be a number not a {type(num)}'
        msg += f'({te})'
        return msg
    except Exception as e:
        return f'-> show_thsep() > ERROR({e})'
 
    return out

In [7]:
# display(n := 98723948759.1234560001)
# # display(n := np.pi)
# # display(n := 98723948759)
# display(f'{n:,}')
# show_thsep(n)


In [8]:
# show_thsep?

In [9]:
# # show_thsep test
display(n := '98723948759.34354')
display(show_thsep(n))         # '-> show_thseps() >> ERROR: argument must be a number (int or float)'

display(n := 98723948759.34354)
display(show_thsep(n, '|'))    # "-> show_thseps() >> ERROR: sep must be ';', '_', or ':'"

display(show_thsep(None))

display(n := 98723948759.34354)
display(show_thsep(n))

display(n := 5)
display(show_thsep(n))    

display(n := 47.825)
display(show_thsep(n))   

display(n := 00.4512)
display(show_thsep(n))   

display(n := 250327.63)
display(show_thsep(n))    

'98723948759.34354'

"-> show_thsep() > ValueError(Cannot specify ',' with 's'.)"

98723948759.34354

"-> show_thsep() > ValueError(Unknown format code '|' for object of type 'float')"

"-> show_thsep() > TypeError: argument must be a number not a <class 'NoneType'>(unsupported format string passed to NoneType.__format__)"

98723948759.34354

'98,723,948,759.34354'

5

'5'

47.825

'47.825'

0.4512

'0.4512'

250327.63

'250,327.63'

## 3. show_tharrsep function

[# Appendix 1 - Functions](#appendix-1---functions)

In [10]:
# function show_tharr()

def show_tharrsep(arr: np.ndarray, sep: str = '_') -> np.ndarray[str]:
    '''Show numeric elements as str with thousands
    separator within a numpy array
    
    arr: numpy ndarray genuine dims valid: [0,1,2,3]
    sep: separator, valid are: ',' or '_' (default)
    '''
    if not isinstance(arr, np.ndarray):
        return "-> show_tharrsep() > ERROR: argument not an np.ndarray"
    
    arr = arr.squeeze()     # for cases w/artificial dims
    if arr.ndim > 3:
        return "-> show_tharrsep() > ERROR: array whose dimensions exceed three"
    
    arr = np.atleast_3d(arr)
    ret_arr = np.ones_like(arr, dtype='>U32')
    for tbl in range(arr.shape[0]):
        for row in range(arr.shape[1]):
            for col in range(arr.shape[2]):
                ret_arr[tbl, row, col] = show_thsep(arr[tbl, row, col],
                                                    sep=sep)

    return ret_arr.squeeze()

In [11]:
display(arr_3D)
# a6 = np.array([arr_3D], [arr_3D])
a6 = np.stack((arr_3D, arr_3D))
print(show_attr('a6'))
show_tharrsep(a6)

array([[[ 10000.  ,  10003.  ,  10006.  ,  10009.  ,  10012.  ],
        [ 10015.  ,  10018.  ,  10021.  ,  10024.  ,  10027.  ],
        [ 10030.  ,  10033.  ,  10036.  ,  10039.  ,  10042.  ]],

       [[ 59156.76,  38914.57, 460820.78, 202886.35, 259803.92],
        [ 65592.99,  23587.59,  73458.56, 359879.  , 393245.79],
        [154989.46, 378013.24, 476440.5 , 409446.9 , 169135.64]]])

 a6: | shape: (2, 2, 3, 5) | ndim: 4 | size: 60 | dtype: float64 


'-> show_tharrsep() > ERROR: array whose dimensions exceed three'

In [12]:
arr_pru = np.arange(100000, 100050, 5, dtype=float).reshape(2,5)
display(arr_pru)
show_tharrsep(arr_pru)

array([[100000., 100005., 100010., 100015., 100020.],
       [100025., 100030., 100035., 100040., 100045.]])

array([['100_000.0', '100_005.0', '100_010.0', '100_015.0', '100_020.0'],
       ['100_025.0', '100_030.0', '100_035.0', '100_040.0', '100_045.0']], dtype='>U32')

In [13]:
display(show_tharrsep(float_rand))
display(show_tharrsep(arr_1D))
display(show_tharrsep(arr_3D))
display(show_tharrsep(float_rand[0], sep=','))
display(show_tharrsep(np.array([[[[[587663.787]]]]])))
display(show_tharrsep(587663.787))

array([['59_156.76', '38_914.57', '460_820.78', '202_886.35', '259_803.92'],
       ['65_592.99', '23_587.59', '73_458.56', '359_879.0', '393_245.79'],
       ['154_989.46', '378_013.24', '476_440.5', '409_446.9', '169_135.64']], dtype='>U32')

array(['65_592.99', '23_587.59', '73_458.56', '359_879.0', '393_245.79'], dtype='>U32')

array([[['10_000.0', '10_003.0', '10_006.0', '10_009.0', '10_012.0'],
        ['10_015.0', '10_018.0', '10_021.0', '10_024.0', '10_027.0'],
        ['10_030.0', '10_033.0', '10_036.0', '10_039.0', '10_042.0']],

       [['59_156.76', '38_914.57', '460_820.78', '202_886.35', '259_803.92'],
        ['65_592.99', '23_587.59', '73_458.56', '359_879.0', '393_245.79'],
        ['154_989.46', '378_013.24', '476_440.5', '409_446.9', '169_135.64']]], dtype='>U32')

array(['59,156.76', '38,914.57', '460,820.78', '202,886.35', '259,803.92'], dtype='>U32')

array('587_663.787', dtype='>U32')

'-> show_tharrsep() > ERROR: argument not an np.ndarray'

## OLD - versions

In [14]:
# Function show_thsep

def show_thsepV(num: float, sep: str = ',') -> str:
    '''Show a number as str with thousands separator
    
    num: a real number (int or float)
    sep: separator, valid are: ','or '_'.
    '''

    if not (isinstance(num, int) or isinstance(num, float) or
        isinstance(num, np.number)):
        return f'-> show_thsep() >> ERROR: argument must be \
a number not a {type(num)}'
    
    if not (sep == ',' or sep == '_'):
        return "-> show_thsep() >> ERROR: sep must be ',' or '_'"
 
    return f'{num:{sep}}'

In [15]:
# Function show_attr def

def show_attrV(arrnm: str) -> str:
    ''' Show numpy ndarray principal attributes
    
    arrnm: array name. Must exist en the main program body
    --> CAN NOT be call inside other function
    '''
    
    if not isinstance(arrnm, str):
          return '-> show_attr() >> ERROR: argument must be an string!'
    
    strout = f' {arrnm}: '
    for attr in ('shape', 'ndim', 'size', 'dtype'):     #, 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

In [16]:
# Function show_attr def

def show_attrV(arr: np.ndarray) -> str:
      ''' Show numpy ndarray principal attributes
       
      arrnm: array name. Must exist en the main program body
      --> CAN NOT be call inside other function
      '''
    
      if not isinstance(arr, np.ndarray):
            return '-> show_attr() >> ERROR: argument must be an string!'

      strout = f'{arr=}'[:f'{arr=}'.find('=')]
      strout += f'| .shape: {arr.shape} '
      strout += f'| .ndim: {arr.ndim} '
      strout += f'| .size: {arr.size} '
      strout += f'| .dtype: {arr.dtype} '

      return strout

In [17]:
var = 'Solo una var'
# ix = f'{var=}'.find('=')
# f'{var=}'[:ix]
print(f'{var= }')
f'{var=}'[:f'{var=}'.find('=')]


# f'{int_rand = }'


var= 'Solo una var'


'var'

In [18]:
# Function show_thsep

def show_thsepV(num: float, sep: str = ',') -> str:
    '''Show num as str with thousands separator
    
    num: a real number (int or float)
    sep: separator, valid are: ';', '_', or ':'
    '''

    if not (isinstance(num, int) or isinstance(num, float) or
        isinstance(num, np.number)):
        return f'-> show_thsep() >> ERROR: argument must be \
a number not a {type(num)}'
    
    if not (sep == ',' or sep == '_'):
        return "-> show_thsep() >> ERROR: sep must be ',' or '_'"

    n_str = str(num)
    dec_ix = n_str.find('.')        # decimal sep index
    if dec_ix > -1:                 # dec_part exist
        dec_part = n_str[dec_ix:]
        int_pr = n_str[:dec_ix][::-1]
    else:                           # there's no dec_part
        dec_part = ''
        int_pr = n_str[::-1]

    int_part = ''
    for dig in range(len(int_pr)):  # for e/digit in int_pr
        int_part += int_pr[dig]
        # every 3 dig add sep but not for the last (1st not-reversed)
        if (dig + 1) % 3 == 0 and dig != (len(int_pr) - 1):
            int_part += sep
    
    return int_part[::-1] + dec_part

In [19]:
# OLD w_out np.atleast_3d
def show_tharr(arr: np.ndarray, sep: str = '_') -> np.ndarray[str]:

    if not isinstance(arr, np.ndarray):
        return "-> show_tharrsep >> ERROR: not an np.ndarray"
    
    arr = arr.squeeze()     # for cases w/artificial dims

    if arr.ndim == 0:
        arr = np.reshape(arr, (1, 1, 1))
    elif arr.ndim == 1:
        arr = np.reshape(arr, (1, 1, arr.shape[0]))
    elif arr.ndim == 2:
        arr = np.reshape(arr, (1, arr.shape[0], arr.shape[1]))
    elif arr.ndim > 3:
        print("-> show_tharrsep >> ERROR: array ndim out of range")

    ret_arr = np.ones_like(arr, dtype='>U32')
    for tbl in range(arr.shape[0]):
        for row in range(arr.shape[1]):
            for col in range(arr.shape[2]):
                ret_arr[tbl, row, col] = show_thsep(arr[tbl, row, col],
                                                    sep=sep)

    return ret_arr.squeeze()


In [20]:
display(cero := np.array(150000.7))
print(show_attr('cero'))

display(one := np.array([1,200000000.986,3]))
print(show_attr('one'))

display(two := np.array([[[[[10000,2,3000.76], [4,500000.98,6]]]]]))
print(show_attr('two'))

display(t := show_tharr(two))
print(show_attr('t'))

array(150000.7)

 cero: | shape: () | ndim: 0 | size: 1 | dtype: float64 


array([1.00000000e+00, 2.00000001e+08, 3.00000000e+00])

 one: | shape: (3,) | ndim: 1 | size: 3 | dtype: float64 


array([[[[[ 10000.  ,      2.  ,   3000.76],
          [     4.  , 500000.98,      6.  ]]]]])

 two: | shape: (1, 1, 1, 2, 3) | ndim: 5 | size: 6 | dtype: float64 


array([['10_000.0', '2.0', '3_000.76'],
       ['4.0', '500_000.98', '6.0']], dtype='>U32')

 t: | shape: (2, 3) | ndim: 2 | size: 6 | dtype: >U32 
