# 2_4 ndarrays

In [32]:
import numpy as np
np.__version__

'2.1.1'

In [33]:
# Functions

def isndarray(el):
        errmsg = f'- Warning --> {el} is not np.ndarray. It is {type(el)}\n'
        if not isinstance(el, np.ndarray):
                print(errmsg)
                return False
        return True


def show(*objs: str) -> None:
    ''' Display numpy.ndarrays objects and some of its more important attributes

    All arguments must be strings.
    can pass a variable number of non-keyworded arguments.
    Return None, only print info -> FUTURE make an string with all the info as return
    '''
    for obj in objs:
        if not isinstance(obj, str):
            print(f'ERROR! --> ArgumentS of show() function must be strings')
            print(f'"{obj}" is not an String')
            continue

        try:
            robj = eval(obj)
        except NameError:
            robj = obj
        if not isndarray(robj):
                continue

        print(f'{obj} -> {type(robj)}:\n{"-" * 80}')
        display(robj)
        print(robj)
        for attr in ('shape', 'ndim', 'size'):  #, 'dtype'):  #, 'itemsize'):
            obj_attr = obj + '.' + attr
            print(f'{obj_attr} = {eval(obj_attr)}  |  ',end="")
        print('\n')     

In [34]:
# 1-Dimensional array - Part of a line - values on a single row or column
array_a = np.array([1,2,3])     # 1-Dimensional array
show('array_a')
# ndarray -> N-Dimensional array

array_a -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------


array([1, 2, 3])

[1 2 3]
array_a.shape = (3,)  |  array_a.ndim = 1  |  array_a.size = 3  |  



In [35]:
# 2-dimensional array - Part of a plane - A collection of rows and columns
array_b = np.array([[7,8,9], [10,11,12]])
show('array_b')

array_b -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------


array([[ 7,  8,  9],
       [10, 11, 12]])

[[ 7  8  9]
 [10 11 12]]
array_b.shape = (2, 3)  |  array_b.ndim = 2  |  array_b.size = 6  |  



In [36]:
# last 2-dim array is a table consisting of 2 rows
# each row is an array (1-dim array) - each row has 3 values (3 scalars, 0-dim array)
# a 2 x 3 table - array_b.shape = (2, 3) -> type tuple - 2 rows 3 columns
display(array_b.shape[0] )      # num of rows - 1st dimension of our 2-d array
array_b.shape[1]                # num of columns - 2nd dimension

2

3

In [37]:
# 0-dimensional arrays, scalars
array_c = np.array(13)
show('array_c')

array_c -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------


array(13)

13
array_c.shape = ()  |  array_c.ndim = 0  |  array_c.size = 1  |  



In [38]:
# scalar defined with one bracket => 1-dim array
array_d = np.array([15])
show('array_d')

array_d -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------


array([15])

[15]
array_d.shape = (1,)  |  array_d.ndim = 1  |  array_d.size = 1  |  



In [39]:
# scalar defined with two brackets => 2-dim array
array_e = np.array([[15]])
show('array_e')
# Even if we need to pass a single value it might have to be expressed as a small
#  array or matrix.
# Certain functions and methods require inputs as a fixed number of dimensions
# How many dimensions your array contains? - look at the code and check de number of
# opening or closing brackets you have

array_e -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------


array([[15]])

[[15]]
array_e.shape = (1, 1)  |  array_e.ndim = 2  |  array_e.size = 1  |  



### ndarrays can containg:
- single scalars, sequence of numbers, tables of values (sequence or collection of tables). An more...
- computational stable and universally accepted in the Python comunity