# 2_5 arrays vs list (np ndarrays vs pure python lists)

In [78]:
import numpy as np
np.__version__

'2.1.1'

In [3]:
# Fibonacci Generator and Function


def fibo_gen(num_elements: int) -> GeneratorExit:

    if not isinstance(num_elements, int) or num_elements < 1:
        return  # to avoid execution error if the argument passed is invalid
    
    a, b = 0, 1
    for _ in range(num_elements):
        fib_num = a
        a, b = b, b + a
        yield(fib_num)



def fibo_func(num_elements: int) -> list:

    if not isinstance(num_elements, int) or num_elements < 1:
        return f'ERROR! --> fibo_func accept only an integer > 0 as parameter'
    
    a, b = 0, 1
    result = [a]
    for _ in range(num_elements - 1):
        result.append(b)
        a, b = b, b + a
    return result

[]
ERROR! --> fibo_func accept only an integer > 0 as parameter
[]
ERROR! --> fibo_func accept only an integer > 0 as parameter
[]
ERROR! --> fibo_func accept only an integer > 0 as parameter
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [80]:
# General Functions

def isndarray(el):
        errmsg = f'- Warning --> {el} is not np.ndarray. It is {type(el)}\n'
        if not isinstance(el, np.ndarray):
                print(errmsg)
                return False
        return True


def show_array(*objs: str) -> None:
    ''' Display numpy.ndarrays objects and some of its more important attributes

    All arguments must be strings.
    can pass a variable number of non-keyworded arguments.
    Return None, only print info -> FUTURE make an string with all the info as return
    '''
    for obj in objs:
        if not isinstance(obj, str):
            print(f'ERROR! --> ArgumentS of show_array() function must be strings')
            print(f'"{obj}" is not an String')
            continue

        try:
            robj = eval(obj)
        except NameError:
            robj = obj
        if not isndarray(robj):
                continue

        print(f'{obj} -> {type(robj)}:\n{"-" * 80}')
        display(robj)
        print(robj)
        for attr in ('shape', 'ndim', 'size'):  #, 'dtype'):  #, 'itemsize'):
            obj_attr = obj + '.' + attr
            print(f'{obj_attr} = {eval(obj_attr)}  |  ',end="")
        print('\n')     

In [81]:
list_0 = [1,2,3,4,5,6]
print(list_0)
show_array('list_0')
type(list_0)

[1, 2, 3, 4, 5, 6]
- Warning --> [1, 2, 3, 4, 5, 6] is not np.ndarray. It is <class 'list'>



list

In [82]:
list_a = [[1,2,3], [4,5,6]]
print(list_a)
show_array('list_a')
type(list_0)

[[1, 2, 3], [4, 5, 6]]
- Warning --> [[1, 2, 3], [4, 5, 6]] is not np.ndarray. It is <class 'list'>



list

In [83]:
array_a = np.array(list_a)
show_array('array_a')

array_a -> <class 'numpy.ndarray'>:
--------------------------------------------------------------------------------


array([[1, 2, 3],
       [4, 5, 6]])

[[1 2 3]
 [4 5 6]]
array_a.shape = (2, 3)  |  array_a.ndim = 2  |  array_a.size = 6  |  



In [84]:
''' list_a.shape '''

# ---------------------------------------------------------------------------
# AttributeError                            Traceback (most recent call last)
# Cell In[21], line 1
# ----> 1 list_a.shape

# AttributeError: 'list' object has no attribute 'shape'

' list_a.shape '

In [85]:
# Actually lists objects don't have attributes, only methods
# - https://docs.python.org/3/tutorial/datastructures.html

list.__dict__.keys()
#list.__dict__

dict_keys(['__new__', '__repr__', '__hash__', '__getattribute__', '__lt__', '__le__', '__eq__', '__ne__', '__gt__', '__ge__', '__iter__', '__init__', '__len__', '__getitem__', '__setitem__', '__delitem__', '__add__', '__mul__', '__rmul__', '__contains__', '__iadd__', '__imul__', '__reversed__', '__sizeof__', 'clear', 'copy', 'append', 'insert', 'extend', 'pop', 'remove', 'index', 'count', 'reverse', 'sort', '__class_getitem__', '__doc__'])

In [86]:
print(len(list_a))
print(len(list_0))
len(array_a)

2
6


2

In [87]:
# print(len(list_0[1]))     TypeError: object of type 'int' has no len()
len(list_a[1])

3

## Array operations work elmentwise
- list operations don't.

In [88]:
list_b = list_a[0] + list_a[1]      # Concatenation of sublists 
array_b = array_a[0] + array_a[1]   # Aritmetic sum of elements in the same position

display(list_b)
display(array_b)
# Arrays compute the element of one array to its corresponding element in a different
#  array

[1, 2, 3, 4, 5, 6]

array([5, 7, 9])

### ndarrays have the added benefit of using built-in functions and methods.
- Ex. if we want to find the squared root of the values of an array:

In [89]:
# Cause of the built in methods of np is not necessary to import the math module
# Only to exemplify
import math

In [90]:
#list_sqrt = math.sqrt(list_a)   # TypeError: must be real number, not list
#list_a[1,0] # TypeError: list indices must be integers or slices, not tupl
print(math.sqrt(list_a[1][0]))
math.sqrt(array_a[1,0])

2.0


2.0

In [91]:
# Elementwise functionality is a great advantage arrays have over lists
# when it comes to computations.
np.sqrt(array_a)


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## jm* Rows of different sizes (lengths)

In [92]:
list_1 = [list(range(1, 4)), list(fibo_gen(8))]
list_1

[[1, 2, 3], [0, 1, 1, 2, 3, 5, 8, 13]]

In [94]:
for i in range(2):
    print(len(list_1), end='  -  ')
    print(len(list_1[i]))

2  -  3
2  -  8


In [95]:
array_1 = np.array(list_1)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.