# 3_1 NumPy Indexing

In [38]:
import numpy as np
np.__version__

'2.1.1'

In [39]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
display(array_a[0])
display(array_a[1])
#array_a[2]  # IndexError: index 2 is out of bounds for axis 0 with size 2

array([1, 2, 3])

array([4, 5, 6])

In [41]:
display(array_a[0][1])
display(array_a[0,1])
#array_a[1,8]    # IndexError: index 8 is out of bounds for axis 1 with size 3
# axis 0 (rows ) - axis 1 (cols)


np.int64(2)

np.int64(2)

In [42]:
# Indexing an entire row (first row - row[0])
display(array_a[0])

# INTERVAL Indices - Slices
display(array_a[0,:])      
# (array_a[0,0:3]) - (array_a[0,:3]) - (array_a[0,0:])

array([1, 2, 3])

array([1, 2, 3])

In [44]:
# Indexing an entire col (Second col, col[1]) - INTERVAL Indices, Slices
display(array_a[:,1])      
display(array_a[0:,1])

array([2, 5])

array([2, 5])

## Negative Indices

In [45]:
array_b = array_a[1]
array_b

array([4, 5, 6])

In [47]:
display(array_b[-1])
display(array_b[-3])
# for i in range(-1,-4,-1):
#     print(array_b[i], end='  ')

np.int64(6)

np.int64(4)

In [49]:
array_a[-1]

array([4, 5, 6])

In [50]:
display(array_a[-2])
display(array_a[-2, -3])
array_a[-1,-2]


array([1, 2, 3])

np.int64(1)

np.int64(5)