# 3_3 Elementwise Properties of Arrays

In [2]:
import numpy as np
np.__version__

'2.1.1'

In [3]:
array_a = np.array([7,8,9])
array_b = np.array([[1,2,3], [4,5,6]])
display(array_a)
array_b

array([7, 8, 9])

array([[1, 2, 3],
       [4, 5, 6]])

### - Elementwise: whatever mathematical computation we are conducting, we are doing it to each element of the array 

In [14]:
# Operations with one scalar (Sum and subs permitted in Numpy but not in Linear Algebra)
display(array_a + 2)
display(array_b + 2)
display(array_a - 1)
display(array_b - 1)
display(array_a + np.array(2))
display(array_a + np.array([2]))
display(array_a + np.array([[[2]]]))

array([ 9, 10, 11])

array([[3, 4, 5],
       [6, 7, 8]])

array([6, 7, 8])

array([[0, 1, 2],
       [3, 4, 5]])

array([ 9, 10, 11])

array([ 9, 10, 11])

array([[[ 9, 10, 11]]])

In [5]:
# Multiplication (or div) of arrays and one scalar (valid in Linear Algebra: )
display(array_a * 2)
display(array_b / 2)

array([14, 16, 18])

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [8]:
### - Very different when using List
list_a = [1, 2, 3]
#list_a + 2      # TypeError: can only concatenate list (not "int") to list
list_a + [2]    # Not math sum, just concatenation


[1, 2, 3, 2]

In [11]:
list_a * 2      # New list that is twice list_a

[1, 2, 3, 1, 2, 3]

In [17]:
# Array vs array math operations
display(array_a + array_b[0,:])      # Elementwise addition
display(array_a - array_b[1,:])      # Elementwise subtraction
display(array_b[0,:] * array_a)     

array([ 8, 10, 12])

array([3, 3, 3])

array([ 7, 16, 27])

### Operations between arrays of diff. dimensions?
- Not valid in Linear Algebra?
#### - The shapes of the arrays need to be *compatible*
- The lenght of the 1-D array must match the *lenght* of the 2-D array.
- When it comes to 2D arrays, we use *lenght* to reffer to the size of its elements (rows).

In [22]:
display(array_a + array_b)
display(array_a * array_b)  # Elementwise * between a_a and e/row of a_b
display(array_a - array_b)
display(array_b - array_a)
display(array_a / array_b)
display(array_b / array_a)
# Broadcasting 

array([[ 8, 10, 12],
       [11, 13, 15]])

array([[ 7, 16, 27],
       [28, 40, 54]])

array([[6, 6, 6],
       [3, 3, 3]])

array([[-6, -6, -6],
       [-3, -3, -3]])

array([[7.  , 4.  , 3.  ],
       [1.75, 1.6 , 1.5 ]])

array([[0.14285714, 0.25      , 0.33333333],
       [0.57142857, 0.625     , 0.66666667]])