# 3_4 Types of Data Supported by NumPy

In [2]:
import numpy as np
np.__version__

'2.1.1'

In [7]:
array_a = np.array([[1,2,3], [4,5,6]])
display(array_a)
array_a.dtype

array([[1, 2, 3],
       [4, 5, 6]])

dtype('int64')

In [10]:
display(np.array([[1,2,3], [4,5,6]], dtype = 'float16'))
display(np.array([[1,2,3], [4,5,6]], dtype = np.float32))
display(np.array([[1,2,3], [4,5,6]], dtype = np.complex64))

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

In [16]:
display(np.array([[1,2,3], [4,5,6]], dtype = np.bool))
display(np.array([[1,-2,0], [-4,0,6]], dtype = np.bool))
display(np.array([[1,-2,0], [-4,0,6]], dtype = np.bool_))
display(np.array([[1,-2,0], [-4,0,6]], dtype = bool))

array([[ True,  True,  True],
       [ True,  True,  True]])

array([[ True,  True, False],
       [ True, False,  True]])

array([[ True,  True, False],
       [ True, False,  True]])

array([[ True,  True, False],
       [ True, False,  True]])

In [22]:
display(np.array([[1,2,3], [4,5,6]], dtype = np.str_))
#display(np.array([[1,2,3], [4,5,6]], dtype = np.str))   # `np.str` was a deprecated alias for the builtin `str`
# - https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
display(np.array([[1,2,3], [4,5,6]], dtype = str))
display(np.array([[1,2,3], [4,5,6]], dtype = 'U3'))
display(np.array([[1,2,3], [4,5,6]], dtype = object))
display(np.array([[1,2,303], [4,5,6]], dtype = str))
display(np.array([[1,2,303], [4,5,6]], dtype = 'str'))


array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U3')

array([[1, 2, 3],
       [4, 5, 6]], dtype=object)

array([['1', '2', '303'],
       ['4', '5', '6']], dtype='<U3')

array([['1', '2', '303'],
       ['4', '5', '6']], dtype='<U3')