# 3_5 Characteristics of NumPy Functions - Universal Functions
- https://numpy.org/doc/stable/reference/ufuncs.html

- Functions that operate element by element on whole arrays.
- Supporting array broadcasting, type casting, and several other standard features.
- We´ll examine several features and parameters that most NumPy functions support.
- *Universal* parameters -> closely ttied -> *Universal* functions.
- Mathematical Ops, Trigonometric and Comparison functions.
- Broadcasting, Type Casting, and Computing over a given axis.

In [2]:
import numpy as np
np.__version__

'2.1.1'

In [5]:
array_a = np.array([1,2,3])                 # row 1-D 
array_b = np.array([[1], [2]])              # 1 col 2-D
matrix_c = np.array([[1,2,3], [4,5,6]])     # 2x3 2-D

for arr in (array_a, array_b, matrix_c):
    display(arr)

array([1, 2, 3])

array([[1],
       [2]])

array([[1, 2, 3],
       [4, 5, 6]])

### Broadcasting:
- Used when we want to conduct element-wise ops, but have elements of different sizes and/or dimensions
- We can *broadcast* the smaller var and create a broadcast version with the size of the larger one.
- Stretching one var (the smaller) over the other to produce an output with the same shape as the larger one.

In [6]:
# Example - row broadcast. Same as array_b + matrix_c
np.add(array_a, matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [7]:
# Example - col broadcast
np.add(array_b, matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

### Broadcasting Rules:
1. The arrays have the same shape (need to broadcast?).
2. The arrays have the same number of dimensions, and the length of each dim is either common or 1.
3. The arrays that have too few dimensions can have their shapes altered with a dimension 1, to satisfy the second rule ¡?

In [12]:
# Ex of 1. (Broadcasting ¡?)
display(np.add(matrix_c, matrix_c))
display(np.add(matrix_c, -1 * matrix_c))
matrix_c - matrix_c


array([[ 2,  4,  6],
       [ 8, 10, 12]])

array([[0, 0, 0],
       [0, 0, 0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
# Ex of 2.
display(array_a, array_b)
np.add(array_a, array_b)

array([1, 2, 3])

array([[1],
       [2]])

array([[2, 3, 4],
       [3, 4, 5]])

In [19]:
# Other examples of 3.
array_z = np.array([100,200,300])
matrix_d = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]])
display(array_z, matrix_d)
np.add(array_z, matrix_d)


array([100, 200, 300])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

array([[101, 202, 303],
       [104, 205, 306],
       [107, 208, 309],
       [110, 211, 312],
       [113, 214, 315]])