# 3_5 Characteristics of NumPy Functions - Universal Functions
- https://numpy.org/doc/stable/reference/ufuncs.html

- Functions that operate element by element on whole arrays.
- Supporting array broadcasting, type casting, and several other standard features.
- We´ll examine several features and parameters that most NumPy functions support.
- *Universal* parameters -> closely ttied -> *Universal* functions.
- Mathematical Ops, Trigonometric and Comparison functions.

## Broadcasting, Type Casting, and Computing over a given axis.

In [10]:
import numpy as np
np.__version__

'1.26.4'

In [11]:
array_a = np.array([1,2,3])                 # row 1-D 
array_b = np.array([[1], [2]])              # 1 col 2-D
matrix_c = np.array([[1,2,3], [4,5,6]])     # 2x3 2-D

for arr in (array_a, array_b, matrix_c):
    display(arr)

array([1, 2, 3])

array([[1],
       [2]])

array([[1, 2, 3],
       [4, 5, 6]])

### Broadcasting:
- Used when we want to conduct element-wise ops, but have elements of different sizes and/or dimensions
- We can *broadcast* the smaller var and create a broadcast version with the size of the larger one.
- Stretching one var (the smaller) over the other to produce an output with the same shape as the larger one.

In [12]:
# Example - row broadcast. Same as array_b + matrix_c
np.add(array_a, matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [13]:
# Example - col broadcast
np.add(array_b, matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

### Broadcasting Rules:
1. The arrays have the same shape (need to broadcast?).
2. The arrays have the same number of dimensions, and the length of each dim is either common or 1.
3. The arrays that have too few dimensions can have their shapes altered with a dimension 1, to satisfy the second rule ¡?

In [14]:
# Ex of 1. (Broadcasting ¡?)
display(np.add(matrix_c, matrix_c))
display(np.add(matrix_c, -1 * matrix_c))
matrix_c - matrix_c


array([[ 2,  4,  6],
       [ 8, 10, 12]])

array([[0, 0, 0],
       [0, 0, 0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
# Ex of 2.
display(array_a, array_b)
np.add(array_a, array_b)

array([1, 2, 3])

array([[1],
       [2]])

array([[2, 3, 4],
       [3, 4, 5]])

In [16]:
# Other examples of 3.
array_z = np.array([100,200,300])
matrix_d = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]])
display(array_z, matrix_d)
np.add(array_z, matrix_d)


array([100, 200, 300])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

array([[101, 202, 303],
       [104, 205, 306],
       [107, 208, 309],
       [110, 211, 312],
       [113, 214, 315]])

### Type Casting
- Changing the specific datatype of every element of an array
- Very widely used.
- The preferred way to unify datatypes across a project.

In [17]:
# Broadcasting first, then Type Casting
display(array_b, array_b.dtype)
display(matrix_c, matrix_c.dtype)
np.add(array_b, matrix_c, dtype=np.float32)
# xxx64 is the actual default ¡?(es el que no se muestra)

array([[1],
       [2]])

dtype('int32')

array([[1, 2, 3],
       [4, 5, 6]])

dtype('int32')

array([[2., 3., 4.],
       [6., 7., 8.]], dtype=float32)

In [18]:
# # In previous versions of NumPY, Type Casting in the unfunc not only
# #  change the result but rather change the inputs themselves. NOT Now
# np.add(array_b, matrix_c, dtype=np.str_)
# # UFuncTypeError: ufunc 'add' did not contain a loop with signature matching
# # types (<class 'numpy.dtypes.Int32DType'>, <class 'numpy.dtypes.Int32DType'>) -> <class 'numpy.dtypes.StrDType'>

In [19]:
# jm just a try
matrix_e = np.add(array_b, matrix_c)
display(matrix_e, matrix_e.dtype)
matrix_e.astype(str)

array([[2, 3, 4],
       [6, 7, 8]])

dtype('int32')

array([['2', '3', '4'],
       ['6', '7', '8']], dtype='<U11')

### Running over an Axis
1. NumPy breaks down an ND-array into smaller arrays of (N-1)-many dimensions.
2. Applies the function to each one.
- In a 2-D array we can use this feature to run a function along each row or column
- jm tries latter over a tensor (a collection of 2-D arrays )

In [20]:
display(matrix_c)
display(np.mean(matrix_c))
display(np.mean(matrix_c, axis=0))
display(np.mean(matrix_c, axis=1))

array([[1, 2, 3],
       [4, 5, 6]])

3.5

array([2.5, 3.5, 4.5])

array([2., 5.])

In [21]:
# jm tries
display(matrix_c, matrix_e)
tensor = np.array([matrix_c, matrix_e, [[10,20,30], [40,50,60]]])
tensor

array([[1, 2, 3],
       [4, 5, 6]])

array([[2, 3, 4],
       [6, 7, 8]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 2,  3,  4],
        [ 6,  7,  8]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [22]:
display(np.max(tensor))
display(np.max(tensor, axis=0))
display(np.max(tensor, axis=1))

60

array([[10, 20, 30],
       [40, 50, 60]])

array([[ 4,  5,  6],
       [ 6,  7,  8],
       [40, 50, 60]])

## JM - xtraExrcises

In [23]:
display(array_a)
display(array_b)
display(matrix_c)

array([1, 2, 3])

array([[1],
       [2]])

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# Broadcast Rule #1 - same shape 
display(matrix_c * 2)
np.add(matrix_c, matrix_c)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
# Broadcast Rule #2 - same dim and length of e/dim common or 1 ¡?
np.add(array_a, array_b)

array([[2, 3, 4],
       [3, 4, 5]])

In [27]:
# Broadcast Rule #3 - The arrays that have too few dimensions can have their shapes
# altered with a dimension 1, to satisfy the Rule #2
display(np.add(array_a, matrix_c))
display(np.add(array_b, matrix_c))

array([[2, 4, 6],
       [5, 7, 9]])

array([[2, 3, 4],
       [6, 7, 8]])

In [38]:
# Unfunc over a given axis
print(matrix_c.shape, ' - ', matrix_c.dtype, ' - ', matrix_c.ndim)
np.mean(matrix_c, axis=-2)
# axis=0=-2 col; axis=1=-1 row


(2, 3)  -  int32  -  2


array([2.5, 3.5, 4.5])

In [29]:
# Typecasting not only change Output also de inputs dtype
np.add(array_b, matrix_c, dtype=str)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (<class 'numpy.dtypes.Int32DType'>, <class 'numpy.dtypes.Int32DType'>) -> <class 'numpy.dtypes.StrDType'>