# 4_1 Basic Slicing NumPy Arrays

In [2]:
import numpy as np
np.__version__

'2.1.1'

In [3]:
matrix_A = np.array([[1,2,3], [4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Entire matrix using slicing
display(matrix_A[:])
display(matrix_A[:,:])
display(matrix_A[::,::]) # future on thi when practice 'steping'


array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Empty matrices
display(matrix_A[:,0:0])
display(matrix_A[0:0])
matrix_A[0:0].ndim

array([], shape=(2, 0), dtype=int64)

array([], shape=(0, 3), dtype=int64)

2

In [6]:
# Common cases
display(matrix_A[:, 1:])
display(matrix_A[:, :1])
display(matrix_A[:, :2])

array([[2, 3],
       [5, 6]])

array([[1],
       [4]])

array([[1, 2],
       [4, 5]])

In [7]:
# Negative indices
display(matrix_A[-1,:])
matrix_A[:, -1]

array([4, 5, 6])

array([3, 6])

In [12]:
# Something to NOTE - same row different DIM
display(matrix_A[0])        # SPECIFIC Indexing
display(matrix_A[0].ndim)
display(matrix_A[:1])       # INTERVAL Indexing
display(matrix_A[:1].ndim)


array([1, 2, 3])

1

array([[1, 2, 3]])

2