# 4_2 Stepwise Slicing NumPy Arrays

In [2]:
import numpy as np
np.__version__

'2.1.1'

In [3]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [5]:
display(matrix_B[:,:])
matrix_B[::,::]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [11]:
display(matrix_B[::2])
display(matrix_B[:,::2])
display(matrix_B[::,::2])
matrix_B[::2,::2]

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

array([[1, 1, 0],
       [4, 3, 0]])

In [13]:
# Negative values for the step
display(matrix_B[::-2,::2])
display(matrix_B[-1::-2,::2])

array([[4, 3, 0],
       [1, 1, 0]])

array([[4, 3, 0],
       [1, 1, 0]])

In [17]:
# jm Invert all the elements
matrix_C = np.array([[1,2,3], [4,5,6], [7,8,9]])
display(matrix_C)
display(matrix_C[-1::-1,::])                          # Only the rows
display(matrix_C[::,-1::-1])                          # Only the cols
matrix_C[-1::-1,-1::-1]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])