# 4_3 Conditional Slicing NumPy Arrays
- I think 'Conditional' in NumPy don't need slicing in the indices at all

In [2]:
import numpy as np
np.__version__

'2.1.1'

In [3]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [4]:
# jm SIMPLE conditional
matrix_B < 5

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False,  True],
       [ True, False,  True, False,  True]])

In [6]:
# Making just for an slice (first col) of matrix_B
display(matrix_B[:,0])
matrix_B[:,0] > 2


array([1, 3, 4])

array([False,  True,  True])

In [9]:
# The boolean matrices giveme the way to select the values
display(matrix_B)
display(matrix_B[matrix_B < 5])         # All values < 5
display(matrix_B[matrix_B[:,0] > 2])    # filtra las filas para los valores
# de la primera col que son > 2

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

array([1, 1, 1, 2, 0, 3, 4, 4, 3, 0])

array([[3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [10]:
# Of course other comparatives
display(matrix_B[matrix_B == 2])        # all twos
display(matrix_B[matrix_B != 2])
display(matrix_B[matrix_B % 2 != 0])   # all odds numbers 


array([2])

array([1, 1, 1, 0, 3, 6, 6, 7, 4, 4, 5, 3, 8, 0])

array([1, 1, 1, 3, 7, 5, 3])

In [12]:
## More than one condition (& and, | or)
# odds nums >= 3 
display(matrix_B[(matrix_B % 2 != 0) & (matrix_B >= 3)])
# or < 4 or even num
display(matrix_B[(matrix_B < 4) | (matrix_B % 2 == 0)])

array([3, 7, 5, 3])

array([1, 1, 1, 2, 0, 3, 6, 6, 4, 4, 3, 8, 0])