# 4_4 Dimensions and the Squeeze Function
- np.squeeze() is the function but the .squeeze method also exist for the ndarray object.

In [15]:
import numpy as np
np.__version__

'2.1.1'

In [16]:
matrix_D = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [17]:
# Diff. ways to reference the same element - diff dimm arrays results
display(matrix_D[0,0])
#type(matrix_D[0,0])
display(matrix_D[0:1,0])
display(matrix_D[0:1,0:1])


np.int64(1)

array([1])

array([[1]])

In [18]:
print(matrix_D[0,0].shape, matrix_D[0,0].ndim)
print(matrix_D[0,0:1].shape, matrix_D[0,0:1].ndim)
print(matrix_D[0:1,0:1].shape, matrix_D[0:1,0:1].ndim)

() 0
(1,) 1
(1, 1) 2


## The Squeeze Method or Squeeze Function
- Removes all the unnecessary dimensions of an array.
- When we squeeze an array holding a single value along all its axes, we get a single numeric value (but the value is a 0-D array rather than a scalar)

In [19]:
display(matrix_D[0:1,0:1].squeeze())
print(matrix_D[0:1,0:1].squeeze().shape,
       matrix_D[0:1,0:1].squeeze().ndim)

array(1)

() 0


In [20]:
# Squeeze function is another way
np.squeeze(matrix_D[0:1,0])

array(1)

In [22]:
# Example for a vector inside a tensor
v = np.array([[[1,2,3]]])
display(v)
print(v.shape, v.ndim)

array([[[1, 2, 3]]])

(1, 1, 3) 3


In [25]:
vs = v.squeeze()
display(v, vs)
print(vs.shape, vs.ndim)


array([[[1, 2, 3]]])

array([1, 2, 3])

(3,) 1
