# 4_A Practice Exam 1

In [16]:
import numpy as np
np.__version__

'2.1.1'

### 1. Two arrays (not 3?)

In [17]:
a = np.array([10])
b = np.array(3)
c = np.array([[12]])

print(type(a), type(b), type(c))
print(c.shape, c.ndim)
a, b, c

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
(1, 1) 2


(array([10]), array(3), array([[12]]))

In [18]:
# jm remembering squeeze
print(np.squeeze(c).shape, np.squeeze(c).ndim)
np.squeeze(c)

() 0


array(12)

In [19]:
display(a+b)
display(a+c)

array([13])

array([[22]])

In [20]:
print(f'a.dim: {a.ndim}')
print(f'b.dim: {b.ndim}')
print(f'c.dim: {c.ndim}')

a.dim: 1
b.dim: 0
c.dim: 2


### 2. N-Darrays and Lists

In [21]:
r = np.array([[1,2], [3,4], [5,6]])
e = [[1,2], [3,4], [5,6]]

display(r,e)

array([[1, 2],
       [3, 4],
       [5, 6]])

[[1, 2], [3, 4], [5, 6]]

### 3. Indexing and Assigning values

In [22]:
s = np.array([[1,2,3], [4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
#c) assigning with positive and negative index
s[-1] = [1,2,3]
# s[1] = [1,2,3]    # Exactly the same assignment
s

array([[1, 2, 3],
       [1, 2, 3]])

In [24]:
l1 = [1,2,3]
l1

[1, 2, 3]

### 4. Operations between ndarrays

In [25]:
p = np.array([[1,10,3], [1,20,4]])
q = np.array([1,2,3])

display(p,q)

array([[ 1, 10,  3],
       [ 1, 20,  4]])

array([1, 2, 3])

In [26]:
#a) broadcasting ok
np.add(p, q)

array([[ 2, 12,  6],
       [ 2, 22,  7]])

In [27]:
#b) q + q rashaped
display(q.reshape(3,1))
display(np.add(q, q.reshape(3,1)))

array([[1],
       [2],
       [3]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [28]:
#c) Adding List or Scalar to an ndarray. Result --> ndarray
display(q + [1,1,1])
display(q + np.array(1))
display(q + 1)
display(q + np.array([[[1]]]))
display(np.squeeze(q + np.array([[[1]]])))

array([2, 3, 4])

array([2, 3, 4])

array([2, 3, 4])

array([[[2, 3, 4]]])

array([2, 3, 4])

In [29]:
#d) Incompatibility shapes for broadcasting
display(p.reshape(3,2))
# display(p.reshape(3,2) + [1,1,1]) # ValueError: operands could not be broadcast together with shapes (3,2) (3,)
display(p.T)
display(p.reshape(3,2) + p.T)
# display(p.T + [1,1,1])            # ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

array([[ 1, 10],
       [ 3,  1],
       [20,  4]])

array([[ 1,  1],
       [10, 20],
       [ 3,  4]])

array([[ 2, 11],
       [13, 21],
       [23,  8]])

### 5. Slicing

In [30]:
A = np.array([[12,-3,4,7], [23,31,-12,10], [24,9,18,15],
              [81,5,6,1], [-10,18,17,29]])
A

array([[ 12,  -3,   4,   7],
       [ 23,  31, -12,  10],
       [ 24,   9,  18,  15],
       [ 81,   5,   6,   1],
       [-10,  18,  17,  29]])

In [31]:
#d) [::2 -> rows 0,2,4 - 1::3 -> cols 1,]
A[::2,1::3]

array([[-3],
       [ 9],
       [18]])

### 6. Conditional or Boolean Slicing

In [32]:
S = np.array([[1,2,3,4], [12,34,23,22],
              [-2,5,10,90], [89,-25,-18,15]])
S

array([[  1,   2,   3,   4],
       [ 12,  34,  23,  22],
       [ -2,   5,  10,  90],
       [ 89, -25, -18,  15]])

In [33]:
# All positive odds numbers from S
S[(S > 0) & (S % 2 != 0)]

array([ 1,  3, 23,  5, 89, 15])

In [34]:
S[(S[:,:]>0) & (S[:,:]%2==1)]

array([ 1,  3, 23,  5, 89, 15])