# 5 Generating Data with Numpy
# 5_1 Arrays of 0s and 1s - Xs
- np.empty(), np.zeros(), np.ones(), np.full()

In [1]:
import numpy as np
np.__version__

'2.1.1'

In [2]:
array_empty = np.empty(shape=(2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

- np.empty(shape(r,c)), return an array without initializing entries.
- Ergo (no initializing), is the FASTEST way to generate an N-D array.
- Doesn't produce consistent arrays. Some portions of the RAM cuold have diff. values.

In [3]:
array_empty = np.empty(shape=(2,3), dtype=np.int8)
array_empty

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [4]:
array_zeros = np.zeros(shape=(2,3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
array_ones = np.ones(shape=(2,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
array_full = np.full(shape=(2,3), fill_value=2)
print(array_full.dtype)
array_full

int64


array([[2, 2, 2],
       [2, 2, 2]])