# 5 Generating Data with Numpy
# 5_2 ...'_like' functions in NumPy
- np.empty_like(), np.zeros_like(), np.ones_like(), np.full_like()

### Application of *zeros_like* in analysis?
1. Starting point for a planner, where we keep track of how many times we´ve increased or decreased a certain element of an array.
2. A form of 'switch' where we change the values from 0 to 1 (and back), depending on whether elements in certain positions are relevant to us or not.
3. Really useful when working with dummy variables!
4. The general gist of like functions is to create a second array in which we store a value for each element of the original one.
5. Convenient when working with huge databases, since we can create equivalent 0-1 arrays and go through them much faster instead of loading up the entire datasets.

In [20]:
import numpy as np
np.__version__

'2.1.1'

In [21]:
A = np.array([[1,2,3,4,5], [10,20,30,40,50], [91,92,93,94,95]])
print(A.dtype)
A

int64


array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50],
       [91, 92, 93, 94, 95]])

In [22]:
B = np.array([[1,2,3,4,5], [10,20,30,40,50], [91,92,93,94,95]], dtype=np.float16)
B

array([[ 1.,  2.,  3.,  4.,  5.],
       [10., 20., 30., 40., 50.],
       [91., 92., 93., 94., 95.]], dtype=float16)

In [23]:
C = np.array([[1,2,3,4,5], [10,20,30,40,50], [91,92,93,94,95]], dtype=str)
C

array([['1', '2', '3', '4', '5'],
       ['10', '20', '30', '40', '50'],
       ['91', '92', '93', '94', '95']], dtype='<U2')

In [24]:
array_empty_like = np.empty_like(A)
print(array_empty_like.dtype)
array_empty_like

int64


array([[             27,   2865899595824,            1127,
          2865899595952,              27],
       [  2865899595856,            1131,   2865899595952,
                     27,   2865899595888],
       [             20, 140731134367752,               0,
                      0,    158913789953]])

In [25]:
array_zeros_like = np.zeros_like(A)
array_zeros_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
array_ones_like = np.ones_like(A)
print(array_ones_like.dtype)
array_ones_like

int64


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
array_ones_like = np.ones_like(B)
print(array_ones_like.dtype)
array_ones_like

float16


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float16)

In [28]:
array_ones_like = np.ones_like(C)
print(array_ones_like.dtype)
array_ones_like

<U2


array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U2')

In [29]:
array_full = np.full_like(C, fill_value=2)
print(array_full.dtype)
array_full

<U2


array([['2', '2', '2', '2', '2'],
       ['2', '2', '2', '2', '2'],
       ['2', '2', '2', '2', '2']], dtype='<U2')