# 5 Generating Data with Numpy
# 5_3 A Non-Random Sequence of Numbers
- numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)

In [14]:
import numpy as np
np.__version__

'2.1.1'

In [15]:
# range() native Python generator (range object)
print(range(30))
print(type(range(30)))
print(list(range(0,30,3)))
display(list(range(30)))

range(0, 30)
<class 'range'>
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]


[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [16]:
array_rng = np.arange(30)
print(type(array_rng))
array_rng

<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
array_rng = np.arange(stop=30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
# array_rng = np.arange(start=30)
# array_rng   # TypeError: arange() requires stop to be specified.

In [22]:
# With Integer Step
array_rng = np.arange(30, step=3)
array_rng

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [21]:
# With Float Step
array_rng = np.arange(30, step=2.5)
array_rng

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [23]:
# With Float Step Changing the dtype to Integer
array_rng = np.arange(30, step=2.5, dtype=np.int32)
array_rng
# The function works solely within the realm of integers
# The step becomes int too
# We start from 0 and take e/even num until we reach 30¡?
# NO, cause there are 12 original steps of 2.5 between 0-30.
# The funct. assumes we want the same num of elements (interval 2.5)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22], dtype=int32)

- https://numpy.org/doc/stable/reference/generated/numpy.arange.html
- When using a non-integer step, such as 0.1, it is often better to use numpy.linspace.
- numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)[source]


In [26]:
a_linspace = np.linspace(0, 30, num=12, endpoint=False)
a_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [28]:
a_linspace = np.linspace(0, 30, num=12)
a_linspace

array([ 0.        ,  2.72727273,  5.45454545,  8.18181818, 10.90909091,
       13.63636364, 16.36363636, 19.09090909, 21.81818182, 24.54545455,
       27.27272727, 30.        ])

In [29]:
a_linspace = np.linspace(0, 30, num=12, dtype=np.int8)
a_linspace

array([ 0,  2,  5,  8, 10, 13, 16, 19, 21, 24, 27, 30], dtype=int8)