# 5 Generating Data with Numpy
# 5_5 Basic Random Functions in NumPy
- New methods to generate integers and probabilities.


### Integers
- numpy.random.Generator.integers
- random.Generator.integers(low, high=None, size=None, dtype=np.int64, endpoint=False).
- Return random integers from the “discrete uniform” distribution of the specified dtype. If high is None (the default), then results are from 0 to low.

### Probabilities
- The random method isn´t compatible with low and high values since probabilities are always between 0 and 1.

### numpy.random.Generator.choice
- random.Generator.choice(a, size=None, replace=True, p=None, axis=0, shuffle=True) 

In [9]:
import numpy as np
np.__version__

'2.1.1'

In [10]:
# Generator function as gen instead of numpy.random.Generator()
from numpy.random import Generator as gen 
# Bit-generator PCG64 as pcg instead of numpy.random.PCG64()
from numpy.random import PCG64 as pcg

In [14]:
array_RG = gen(pcg(365))
A1 = array_RG.integers(10, size=(5,5))
print(A1.dtype)
display(A1)

int64


array([[0, 7, 6, 7, 8],
       [6, 6, 2, 0, 6],
       [3, 0, 3, 7, 9],
       [1, 1, 8, 7, 4],
       [4, 8, 6, 4, 9]])

In [15]:
array_RG = gen(pcg(365))
array_RG.integers(low=10, high=100, size=(5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]])

In [20]:
# Probabilities
array_RG = gen(pcg(365))
array_RG.random(size=(3,4))
# The values in it are extracted from a continuous uniform distribution.
# Statistically speaking, this means that getting any of the infinitely
# many values in the interval is equally likely here

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599],
       [0.66501486, 0.06559111, 0.71326309, 0.10812106],
       [0.87969046, 0.49405844, 0.82472673, 0.45652944]])

In [21]:
array_RG = gen(pcg(365))
array_RG.choice([1,2,3,4,5], size=(3,4))    # All the outcomes are equally likely
# We haven´t specified fixed probabilities for each element
# The method defaults to using a discrete uniform distibution
# From a Statistical sense this means we have a known finite amount of
# equally likely possible outcomes.

array([[1, 4, 4, 4],
       [5, 4, 4, 2],
       [1, 4, 2, 1]])

In [33]:
# We can manually set the probabilities for each value of the sequence.
array_RG = gen(pcg(365))
array_RG.choice([1,2,3,4,5], p=[0.1,0.1,0.1,0.1,0.6], size=(5,5)) 

array([[5, 5, 5, 3, 5],
       [1, 5, 2, 5, 5],
       [5, 5, 1, 5, 4],
       [3, 5, 5, 5, 5],
       [5, 1, 5, 5, 2]])

In [ ]:
#1 3/25 - #2 2/25 ... #5 17/15 = .68

## Documentation Example
- https://numpy.org/doc/2.0/reference/random/generated/numpy.random.Generator.integers.html

In [19]:
rng = np.random.default_rng()
rng.integers(5, size=(2,5), dtype=np.int8)

array([[4, 2, 3, 3, 3],
       [0, 2, 4, 3, 2]], dtype=int8)