# 5_A Practice Exam 2 
### Generating Data with NumPy
- Non-random data: empty, zeros, ones, full, arange
- Random data: random gen, bit gen, seeds, probability distributios
- Applications of generating pseudo-random data

In [12]:
import numpy as np
np.__version__

'1.26.2'

- numpy.empty(shape, dtype=float, order='C', *, device=None, like=None)
- numpy.zeros(shape, dtype=float, order='C', *, like=None)
- numpy.full(shape, fill_value, dtype=None, order='C', *, device=None, like=None)
- numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None, *, device=None)
- numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)

In [41]:
np.full(shape=(2,3), fill_value=2)
-np.ones(shape=(3,3))

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [39]:
# np.arange(-3, 9, 2)
# np.arange(25)
# np.arange(25,2.5)
np.arange(30,step=1.5)


array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5, 21. , 22.5, 24. , 25.5, 27. , 28.5])

- from numpy.random import Generator as gen     # Generator
- from numpy.random import PCG64 as pcg         # Bit_generator
- class numpy.random.Generator(bit_generator)
- array_RG = gen(pcg(seed=365))
- array_RG.random(size=(5,10))
- random.Generator.integers(low, high=None, size=None, dtype=np.int64, endpoint=False)
- random.Generator.choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)

In [15]:
from numpy.random import Generator as gen 
from numpy.random import PCG64 as pcg

In [16]:
array_RG = gen(pcg(123))
display(array_RG.random(size=(2,3)))
display(array_RG.integers(-3, 9, size=(2,3)))
display(array_RG.choice([-3,9,0,5,-4], p=[0.1, 0.2, 0.1, 0, 0.6], size=(2,3)))

array([[0.68235186, 0.05382102, 0.22035987],
       [0.18437181, 0.1759059 , 0.81209451]])

array([[2, 8, 2],
       [0, 6, 6]], dtype=int64)

array([[-4, -4,  9],
       [-4,  9, -4]])

- random.normal(loc=0.0, scale=1.0, size=None)
- random.poisson(lam=1.0, size=None)
- random.binomial(n, p, size=None)
- random.logistic(loc=0.0, scale=1.0, size=None)

- numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)

- numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+, -./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding=None, *, ndmin=0, like=None)

In [17]:
array_RG.binomial(100, 0.2, size=(2,3))

array([[21, 26, 17],
       [23, 20, 17]], dtype=int64)

In [18]:
array_RG.logistic(9, 1.2, size=(2,3))

array([[7.06207291, 8.98938698, 9.40076211],
       [7.21532507, 3.96992601, 8.86128524]])

In [29]:
array_RG = gen(pcg(seed=365))
c1 = array_RG.normal(loc=3, scale=2, size=500)
c2 = array_RG.exponential(scale=5, size=500)
c3 = array_RG.logistic(loc=10, scale=4, size=500)

A = np.array([c1, c2, c3]).transpose()

A.max()

35.04153699695336

In [26]:
array_RG.exponential(scale=5, size=500)

4.755472718060206

In [38]:
array_RG = gen(pcg(seed=60))
B =array_RG.binomial(n=80, p=0.3, size=(3,3))
B.mean()

25.666666666666668

In [40]:
array_RG = gen(pcg(seed=60))
np.mean(array_RG.binomial(n=80, p=0.3, size=(3,3)))

25.666666666666668