# 5_A Practice Exam 2 
### Generating Data with NumPy
- Non-random data: empty, zeros, ones, full, arange
- Random data: random gen, bit gen, seeds, probability distributios
- Applications of generating pseudo-random data

In [15]:
import numpy as np
np.__version__

'1.26.4'

- numpy.empty(shape, dtype=float, order='C', *, device=None, like=None)
- numpy.zeros(shape, dtype=float, order='C', *, like=None)
- numpy.full(shape, fill_value, dtype=None, order='C', *, device=None, like=None)
- numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None, *, device=None)
- numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)

In [16]:
np.full(shape=(2,3), fill_value=2)
-np.ones(shape=(3,3))

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [17]:
# np.arange(-3, 9, 2)
# np.arange(25)
# np.arange(25,2.5)
np.arange(30,step=1.5)


array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5, 21. , 22.5, 24. , 25.5, 27. , 28.5])

- from numpy.random import Generator as gen     # Generator
- from numpy.random import PCG64 as pcg         # Bit_generator
- class numpy.random.Generator(bit_generator)
- array_RG = gen(pcg(seed=365))
- array_RG.random(size=(5,10))
- random.Generator.integers(low, high=None, size=None, dtype=np.int64, endpoint=False)
- random.Generator.choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)

In [18]:
from numpy.random import Generator as gen 
from numpy.random import PCG64 as pcg

In [19]:
array_RG = gen(pcg(123))
display(array_RG.random(size=(2,3)))
display(array_RG.integers(-3, 9, size=(2,3)))
display(array_RG.choice([-3,9,0,5,-4], p=[0.1, 0.2, 0.1, 0, 0.6], size=(2,3)))

array([[0.68235186, 0.05382102, 0.22035987],
       [0.18437181, 0.1759059 , 0.81209451]])

array([[2, 8, 2],
       [0, 6, 6]], dtype=int64)

array([[-4, -4,  9],
       [-4,  9, -4]])

- random.normal(loc=0.0, scale=1.0, size=None)
- random.poisson(lam=1.0, size=None)
- random.binomial(n, p, size=None)
- random.logistic(loc=0.0, scale=1.0, size=None)

- numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)

- numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+, -./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding=None, *, ndmin=0, like=None)

In [20]:
array_RG.binomial(100, 0.2, size=(2,3))

array([[21, 26, 17],
       [23, 20, 17]], dtype=int64)

In [21]:
m = array_RG.binomial(80, 0.3, size=(3,3))
np.mean(m)

23.22222222222222

In [22]:
array_RG.logistic(9, 1.2, size=(2,3))

array([[11.88465407, 11.22576572,  7.46817385],
       [11.24057241, 10.19812912,  7.85390967]])

In [23]:
array_RG = gen(pcg(seed=365))
c1 = array_RG.normal(loc=3, scale=2, size=500)
c2 = array_RG.exponential(scale=5, size=500)
c3 = array_RG.logistic(loc=10, scale=4, size=500)

A = np.array([c1, c2, c3]).transpose()

A.max()

35.04153699695336

In [24]:
array_RG.exponential(scale=5, size=500)

array([3.46911572e+00, 6.52189720e+00, 1.92948167e+01, 2.40157688e+00,
       7.52677319e+00, 1.56759446e+01, 4.42679316e+00, 4.65500397e-01,
       2.27278000e+00, 1.09505911e+01, 1.51860199e+00, 4.94528193e+00,
       1.25227275e+00, 3.83163194e+00, 3.37313906e+00, 8.13511214e+00,
       7.82166663e+00, 1.55496291e+00, 8.04958591e+00, 1.15325153e+01,
       1.77865736e+00, 5.79793875e+00, 2.20523898e+00, 4.00776042e+00,
       5.29479484e-01, 9.64996474e+00, 1.20498043e+00, 1.04090419e+00,
       6.92062497e+00, 2.46036717e+00, 3.37108590e+00, 1.23385281e+01,
       1.92963838e+01, 3.74908442e+00, 7.04911760e-01, 1.21849771e+00,
       7.20665231e+00, 1.37323758e+00, 1.33799348e-02, 5.01540779e+00,
       3.03827761e-01, 4.01845781e+00, 1.94932456e+00, 3.91097016e+00,
       1.30784710e+01, 2.23125190e+00, 7.51021935e+00, 1.95198450e+00,
       2.53322974e+00, 1.36421971e+01, 2.63410206e+00, 4.80322807e-02,
       1.68222450e+00, 6.95740498e-01, 8.13970501e+00, 3.13829574e+00,
      

In [25]:
array_RG = gen(pcg(seed=60))
B =array_RG.binomial(n=80, p=0.3, size=(3,3))
B.mean()

25.666666666666668

In [26]:
array_RG = gen(pcg(seed=60))
np.mean(array_RG.binomial(n=80, p=0.3, size=(3,3)))

25.666666666666668

In [31]:
# f = np.arange(start=25)
f = np.arange(stop=25, step=2.5)
f = np.arange(start=30, step=1.5)
f

TypeError: arange() requires stop to be specified.