# 6 Importing and Saving Data with NumPy
## 6_1 np.loadtxt() vs np.genfromtxt()
- numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding=None, max_rows=None, *, quotechar=None, like=None)

- numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+, -./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding=None, *, ndmin=0, like=None)

In [13]:
import numpy as np
np.__version__

'1.26.2'

In [14]:
lending_co_data_numeric_1 = np.loadtxt('Lending-Company-Numeric-Data.csv',
                                       delimiter=',')

print(lending_co_data_numeric_1.shape, lending_co_data_numeric_1.ndim,
      lending_co_data_numeric_1.size)

lending_co_data_numeric_1

(1043, 6) 2 6258


array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [15]:
lending_co_data_numeric_2 = np.genfromtxt('Lending-Company-Numeric-Data.csv',
                                          delimiter=',')

print(lending_co_data_numeric_2.shape, lending_co_data_numeric_2.ndim,
      lending_co_data_numeric_2.size)

lending_co_data_numeric_2

(1043, 6) 2 6258


array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [16]:
# txt file with missing values
# lending_co_data_numeric_NAN = np.loadtxt('Lending-Company-Numeric-Data-NAN.csv',
#                                         delimiter=';')

# ValueError: could not convert string '' to float64 at row 11, column 4.

In [17]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                          delimiter=';')

print(lending_co_data_numeric_NAN.shape, lending_co_data_numeric_NAN.ndim,
      lending_co_data_numeric_NAN.size)

lending_co_data_numeric_NAN

(1043, 6) 2 6258


array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [18]:
lending_co_data_numeric_NANstr = np.loadtxt('Lending-Company-Numeric-Data-NAN.csv',
                                            delimiter=';',
                                            dtype=str)

print(lending_co_data_numeric_NANstr.shape, lending_co_data_numeric_NANstr.ndim,
      lending_co_data_numeric_NANstr.size)

lending_co_data_numeric_NANstr

(1043, 6) 2 6258


array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')