# 6 Importing and Saving Data with NumPy
## 6_2 Simple Cleaning when Importing

- numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+, -./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding=None, *, ndmin=0, like=None)

- skip_header, skip_footer, usecols, unpack

In [10]:
import numpy as np
np.__version__

'2.1.1'

In [11]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                          delimiter=';')

print(lending_co_data_numeric_NAN.shape, lending_co_data_numeric_NAN.ndim,
      lending_co_data_numeric_NAN.size)

lending_co_data_numeric_NAN

(1043, 6) 2 6258


array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [12]:
# Exclude first two rows (supposing some title not data)
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                          delimiter=';',
                                          skip_header=2)

print(lending_co_data_numeric_NAN.shape, lending_co_data_numeric_NAN.ndim,
      lending_co_data_numeric_NAN.size)

lending_co_data_numeric_NAN

(1041, 6) 2 6246


array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [13]:
# Exclude last two rowa (supposing some footer no data)
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                            delimiter=';',
                                            skip_footer=2)

print(lending_co_data_numeric_NAN.shape, lending_co_data_numeric_NAN.ndim,
      lending_co_data_numeric_NAN.size)

lending_co_data_numeric_NAN

(1041, 6) 2 6246


array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [14]:
# Select only some columns added to the early excluded
# Exclude last two rows (supposing some footer no data)
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                            delimiter=';',
                                            skip_header=2,
                                            skip_footer=2,
                                            usecols=(5,0,1))

print(lending_co_data_numeric_NAN.shape, lending_co_data_numeric_NAN.ndim,
      lending_co_data_numeric_NAN.size)

lending_co_data_numeric_NAN

(1039, 3) 2 3117


array([[15340.,  1000.,    40.],
       [15321.,  2000.,    40.],
       [13720.,  2000.,    50.],
       ...,
       [16600.,  2000.,    40.],
       [16600.,  2000.,    40.],
       [16600.,    nan,    40.]])

In [15]:
# Unpacking cols in diff vars
col_5, col_0, col_1 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                    delimiter=';',
                                    skip_header=2,
                                    skip_footer=2,
                                    usecols=(5,0,1),
                                    unpack=True)

display(col_5, col_0, col_1)

array([15340., 15321., 13720., ..., 16600., 16600., 16600.])

array([1000., 2000., 2000., ..., 2000., 2000.,   nan])

array([40., 40., 50., ..., 40., 40., 40.])

In [16]:
col_5, col_0, col_1 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                    delimiter=';',
                                    skip_header=2,
                                    skip_footer=2,
                                    usecols=(5,0,1))

ValueError: too many values to unpack (expected 3)