# 6 Importing and Saving Data with NumPy
## 6_3A Exercise
- np.loadtxt()      - faster but more limited, can not manage NANs
- np.genfromtxt()   - slower but more versatil
- np.array_equal()

#### numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding=None, max_rows=None, *, quotechar=None, like=None)
- Load data from a text file.

#### numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+, -./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding=None, *, ndmin=0, like=None)
- Load data from a text file, with missing values handled as specified.
- Each line past the first skip_header lines is split at the delimiter character, and characters following the comments character are discarded.

#### Simple Data Cleaning and Preprocessing w/.genfromtxt()
- skip_header=; skip_footer=; usecols=; unpack=

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [9]:
# Function show_attr

def show_attr(arrnm: str) -> str:
    strout = f' {arrnm}: '

    for attr in ('shape', 'ndim', 'size', 'dtype'):     #, 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

In [11]:
lending_co_lt = np.genfromtxt('Lending-Company-Numeric-Data.csv',
                              delimiter=',')

print(lending_co_lt)
show_attr('lending_co_lt')


[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


' lending_co_lt: | shape: (1043, 6) | ndim: 2 | size: 6258 | dtype: float64 '

In [13]:
col_0 = np.genfromtxt('Lending-Company-Numeric-Data.csv',
                      delimiter=',',
                      usecols=0)

display(col_0)
show_attr('col_0')

array([2000., 2000., 1000., ..., 2000., 1000., 2000.])

' col_0: | shape: (1043,) | ndim: 1 | size: 1043 | dtype: float64 '

In [15]:
col_5, col_1 = np.genfromtxt('Lending-Company-Numeric-Data.csv',
                             delimiter=',',
                             usecols=[5,1],
                             unpack=True)

display(col_5, show_attr('col_5'))
display(col_1, show_attr('col_1'))

array([13621., 15041., 15340., ..., 16600., 15600., 16600.])

' col_5: | shape: (1043,) | ndim: 1 | size: 1043 | dtype: float64 '

array([40., 40., 40., ..., 40., 40., 40.])

' col_1: | shape: (1043,) | ndim: 1 | size: 1043 | dtype: float64 '