# 6 Importing and Saving Data with NumPy
## 6_6A Exercise

#### numpy.save(file, arr, allow_pickle=True, fix_imports=<no value>)
- Save an array to a binary file in NumPy .npy format.
- .save() -> .npy file <- .load()

#### numpy.savez(file, *args, **kwds)
- Save several arrays into a single file in uncompressed .npz format.
- Provide arrays as keyword arguments to store them under the corresponding name in the output file: savez(fn, x=x, y=y).
- If arrays are specified as positional arguments, i.e., savez(fn, x, y), their names will be arr_0, arr_1, etc.
-jm: keywords matrix id, to see them, run 'readed_savez.files'

#### numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
- Save an array to a text file.

In [32]:
import numpy as np
np.__version__

'1.26.4'

In [33]:
# Functions

def show_attr(arrnm: str) -> str:
    strout = f' {arrnm}: '

    for attr in ('shape', 'ndim', 'size', 'dtype', 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

In [34]:
lending_co = np.genfromtxt('Lending-Company-Numeric-Data.csv', delimiter=',')

print(show_attr('lending_co') + '\n')
print(lending_co)

 lending_co: | shape: (1043, 6) | ndim: 2 | size: 6258 | dtype: float64 | itemsize: 8 

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [35]:
np.savetxt('arr_savetxt.csv', lending_co, fmt='%s', delimiter='|')

In [36]:
arr_loaded = np.genfromtxt('arr_savetxt.csv',delimiter='|')

print(show_attr('arr_loaded') + '\n')
arr_loaded

 arr_loaded: | shape: (1043, 6) | ndim: 2 | size: 6258 | dtype: float64 | itemsize: 8 



array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [37]:
# Other tries
np.savetxt('arr_savetxt.csv', lending_co, fmt='%s', delimiter=' |')

In [38]:
arr_loaded = np.genfromtxt('arr_savetxt.csv', delimiter=' |')
                          
print(show_attr('arr_loaded') + '\n' * 2, arr_loaded)
# arr_loaded

 arr_loaded: | shape: (1043, 6) | ndim: 2 | size: 6258 | dtype: float64 | itemsize: 8 

 [[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


### numpy.array_equal(a1, a2, equal_nan=False)

In [39]:
np.array_equal(arr_loaded, lending_co)

True