# 7 Statistics with NumPy
## 7_1 Using Statisticals Functions in NumPy
- There are more statistical NumPy functions than methods.

- Functions enable Broadcast and Typecast

- Called over specific axes.

In [19]:
import numpy as np
np.__version__

'2.1.1'

In [20]:
# Functions

def show_attr(arrnm: str) -> str:
    strout = f' {arrnm}: '

    for attr in ('shape', 'ndim', 'size', 'dtype', 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

In [21]:
A = np.array([[1,0,0,3,1],
              [3,6,6,2,9],
              [4,5,3,8,0]])
A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

### numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

- Compute the arithmetic mean along the specified axis.
- Returns the average of the array elements. The average is taken over the flattened array by default, otherwise over the specified axis. float64 intermediate and return values are used for integer inputs.
- Mean: Mathematical Average of values.

In [22]:
# The mean value for the flattened array (mean of all values)
display(A.mean())
np.mean(A)

np.float64(3.4)

np.float64(3.4)

In [23]:
# First row mean
display(A[0].mean())
display(np.mean(A[0]))
np.mean(A[0,:])

np.float64(1.0)

np.float64(1.0)

np.float64(1.0)

In [24]:
# first col mean
np.mean(A[:,0])

np.float64(2.6666666666666665)

In [25]:
# mean of each of the columns - several means simultaneously
np.mean(A, axis=0)

array([2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333])

In [26]:
# mean of each of the rows
np.mean(A, axis=1)

array([1. , 5.2, 4. ])

In [27]:
# Rows and columns means truncated to int
display(np.mean(A, axis=1, dtype=np.int16))
np.mean(A, axis=0, dtype=np.int16)

array([1, 5, 4], dtype=int16)

array([2, 3, 3, 4, 3], dtype=int16)

### Axis in a tensor

In [28]:
# Matrix def for a 2 x 3 x 5 Tensor
# A already def.
B = np.array([[1,1,1,1,1],
              [2,2,2,2,2],
              [3,3,3,3,3]])

# C = np.array([[9,9,9,9,9],
#               [8,8,8,8,8],
#               [7,7,7,7,7]])

display(A,B)

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [29]:
# The Tensor - A 2x3x5 ndarray
T = np.array([A, B])

print(show_attr('T') + '\n')
T

 T: | shape: (2, 3, 5) | ndim: 3 | size: 30 | dtype: int64 | itemsize: 8 



array([[[1, 0, 0, 3, 1],
        [3, 6, 6, 2, 9],
        [4, 5, 3, 8, 0]],

       [[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]]])

In [30]:
# Mean of each 'deep' axis. Element-wise mean of both tables
np.mean(T, axis=0)
# mean of each element counterpart of tables.

array([[1. , 0.5, 0.5, 2. , 1. ],
       [2.5, 4. , 4. , 2. , 5.5],
       [3.5, 4. , 3. , 5.5, 1.5]])

In [31]:
# Mean of each Col of each Table (2-D array)
np.mean(T, axis=1)
# 1st row: means of cols of Tbl1. 2nd row of Tbl2

array([[2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333],
       [2.        , 2.        , 2.        , 2.        , 2.        ]])

In [32]:
# Mean of each Row of each Table (2-D array)
np.mean(T, axis=2)
# 1st row: means of rows of Tbl1, 2nd row of Tbl2

# ROWS always the LAST axis, and Cols the 2nd last

array([[1. , 5.2, 4. ],
       [1. , 2. , 3. ]])

In [33]:
np.mean(T, axis=3)

AxisError: axis 3 is out of bounds for array of dimension 3