# 7 Statistics with NumPy
## 7_1 Using Statisticals Functions in NumPy
- There are more statistical NumPy functions than methods.

- Functions enable Broadcast and Typecast

- Called over specific axes.

FUTURE: ex. of typecast + try axis in a 2x3x5 (2,3,5) TENSOR 

In [2]:
import numpy as np
np.__version__

'1.26.2'

In [38]:
# Functions

def show_attr(arrnm: str) -> str:
    strout = f' {arrnm}: '

    for attr in ('shape', 'ndim', 'size', 'dtype', 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

In [ ]:
A = np.array([[1,0,0,3,1],
              [3,6,6,2,9],
              [4,5,3,8,0]])
A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

### numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

- Compute the arithmetic mean along the specified axis.
- Returns the average of the array elements. The average is taken over the flattened array by default, otherwise over the specified axis. float64 intermediate and return values are used for integer inputs.

In [5]:
# The mean value for the flattened array (mean of all values)
display(A.mean())
np.mean(A)

3.4

3.4

In [8]:
# First row mean
display(A[0].mean())
display(np.mean(A[0]))
np.mean(A[0,:])

1.0

1.0

1.0

In [9]:
# first col mean
np.mean(A[:,0])

2.6666666666666665

In [10]:
# mean of each of the columns - several means simultaneously
np.mean(A, axis=0)

array([2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333])

In [11]:
# mean of each of the rows
np.mean(A, axis=1)

array([1. , 5.2, 4. ])