# 7 Statistics with NumPy
## 7_2 Mathematical in tis case -> Minimal and Maximal Values in NumPy
#### numpy.min(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>
- Return the minimum of an array or minimum along an axis.
- Exactly the same as numpy.amin() - np.min() and np.amin() are absolutely equivalent and interchangeble (.amin is an alias on .min)
#### numpy.minimum(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature]) = <ufunc 'minimum'>
- Element-wise minimum of array elements.
- Compare two arrays and return a new array containing the element-wise minima. If one of the elements being compared is a NaN, then that element is returned. If both elements are NaNs then the first is returned. The latter distinction is important for complex NaNs, which are defined as at least one of the real or imaginary parts being a NaN. The net effect is that NaNs are propagated.
- Minimum values and several minima values. Latin, minimum is singular and minima is plural.
- Adjective: minimal or maximal value. Noun: the minimum or maximum.
- .reduce() method: if we reduce the inputs of a matrix, we can essentially pass al of its rows as inputs simultaneously.
- np.min() calls np.minimum(), so using the latter is very slightly more efficient.

#### numpy.max(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
- Return the maximum of an array or maximum along an axis.

In [2]:
import numpy as np
np.__version__

'2.1.1'

In [3]:
# Functions

def show_attr(arrnm: str) -> str:
    strout = f' {arrnm}: '

    for attr in ('shape', 'ndim', 'size', 'dtype', 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

In [4]:
A = np.array([[1,0,0,3,1],
              [3,6,6,2,9],
              [4,5,3,8,0]])
A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [5]:
display(np.min(A))
display(np.min(A[0,:]))
display(np.min(A, axis=1))
np.min(A, axis=0)

np.int64(0)

np.int64(0)

array([0, 2, 0])

array([1, 0, 0, 2, 0])

In [6]:
B = np.full_like(A, fill_value=5)
B

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [7]:
np.minimum(A, B)

array([[1, 0, 0, 3, 1],
       [3, 5, 5, 2, 5],
       [4, 5, 3, 5, 0]])

In [8]:
np.minimum(A[0,:], A[2,:])

array([1, 0, 0, 3, 0])

In [12]:
np.minimum(A[:,1], A[:,4])

array([0, 6, 0])

In [18]:
# .reduce() method
display(A)
display(np.maximum.reduce(A))           # max of each col
display(np.minimum.reduce(A))
display(np.maximum.reduce(A, axis=1))   # msx of each row
display(np.minimum.reduce(A, axis=1))

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

array([4, 6, 6, 8, 9])

array([1, 0, 0, 2, 0])

array([3, 9, 8])

array([0, 2, 0])

In [21]:
display(np.min(A, axis=0))      # min of each col
display(np.min(A, axis=1))      # min of each row

array([1, 0, 0, 2, 0])

array([0, 2, 0])

In [33]:
# .min() of the whole matrix with minimum
%time
np.minimum.reduce(A, axis=(0,1))

CPU times: total: 0 ns
Wall time: 0 ns


np.int64(0)

In [30]:
%time
np.min(A)

CPU times: total: 0 ns
Wall time: 0 ns


np.int64(0)

In [10]:
np.maximum(A[0,:], A[:,0])

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

Mathematical functions - Extrema finding

maximum(x1, x2, /[, out, where, casting, ...])
Element-wise maximum of array elements.

max(a[, axis, out, keepdims, initial, where])
Return the maximum of an array or maximum along an axis.

amax(a[, axis, out, keepdims, initial, where])
Return the maximum of an array or maximum along an axis.

fmax(x1, x2, /[, out, where, casting, ...])
Element-wise maximum of array elements.

nanmax(a[, axis, out, keepdims, initial, where])
Return the maximum of an array or maximum along an axis, ignoring any NaNs.

minimum(x1, x2, /[, out, where, casting, ...])
Element-wise minimum of array elements.

min(a[, axis, out, keepdims, initial, where])
Return the minimum of an array or minimum along an axis.

amin(a[, axis, out, keepdims, initial, where])
Return the minimum of an array or minimum along an axis.

fmin(x1, x2, /[, out, where, casting, ...])
Element-wise minimum of array elements.

nanmin(a[, axis, out, keepdims, initial, where])
Return minimum of an array or minimum along an axis, ignoring any NaNs.