# 7 Statistics with NumPy
## 7_3 Excercises

In [1]:
import numpy as np
np.__version__

'1.26.2'

In [2]:
# Functions

def show_attr(arrnm: str) -> str:
    strout = f' {arrnm}: '

    for attr in ('shape', 'ndim', 'size', 'dtype'):     #, 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

#### 1. When calculating the mean of a 2D array using np.mean(matrix_A), NumPy flattens the array into a 1D array and calculates the mean of all elements.
- True
- By default, when no axis is specified in np.mean, the function flattens the input array and computes the mean of all the elements in the array. In contrast, specifying an axis will compute the mean along that specific axis (either rows or columns).

### 2. Given the following code, what will be the output?
- Give your answer rounded to 2 decimal places

In [3]:
14/3, 12/3, 17/3

(4.666666666666667, 4.0, 5.666666666666667)

In [4]:
A = np.array([[1,2,6],
              [10,4,3],
              [3,6,8]])

print(show_attr('A'))
display(A)

result = np.min(np.mean(A, axis=0))
np.round(result, 2)

 A: | shape: (3, 3) | ndim: 2 | size: 9 | dtype: int32 


array([[ 1,  2,  6],
       [10,  4,  3],
       [ 3,  6,  8]])

4.0

#### 3. Given the following code, what will be the output?
- Give your answer rounded to 2 decimal places

In [5]:
23/4

5.75

In [6]:
B = np.array([[4,2,0,5],
              [9,5,3,6],
              [3,6,8,5]])

print(show_attr('B'))
display(B)

r1 = np.maximum(B[0], B[-1])
np.mean(r1)

 B: | shape: (3, 4) | ndim: 2 | size: 12 | dtype: int32 


array([[4, 2, 0, 5],
       [9, 5, 3, 6],
       [3, 6, 8, 5]])

5.75

#### Given that the variable matrix is a 2D NumPy array, categorize the following NumPy functions based on the type of output they would produce - a single number, or a list/array.
- Single number:
    - np.percentile(matrix, 0.2)
    - np.amax(matrix)
    - np.ptp(matrix[0])
    - np.min(np.mean(matrix, axis=0))
- Array:
    - np.minumun.reduce(matrix)
    - np.mean(matrix, axis=0)
    - np.ptp(matriz, axis=0)

In [7]:
# Single number
display(A)
display(np.percentile(A, 0.2))
display(np.percentile(A, 20))
display(np.amax(A))
display(np.ptp(A))
display(np.min(np.mean(A, axis=0)))


array([[ 1,  2,  6],
       [10,  4,  3],
       [ 3,  6,  8]])

1.016

2.6

10

9

4.0

In [8]:
# Array
display(np.maximum.reduce(A))
display(np.mean(A, axis=0))
display(np.ptp(A, axis=0))

array([10,  6,  8])

array([4.66666667, 4.        , 5.66666667])

array([9, 4, 5])

In [25]:
# Bit more on .reduce
C = np.array([[4,2,0,5],
              [9,5,3,6],
              [3,6,8,5]])

print(show_attr('C'))
display(C)

display(np.minimum.reduce(C))   # minimum in each col of the 3 rows
display(np.min(C, axis=0))

 C: | shape: (3, 4) | ndim: 2 | size: 12 | dtype: int32 


array([[4, 2, 0, 5],
       [9, 5, 3, 6],
       [3, 6, 8, 5]])

array([3, 2, 0, 5])

array([3, 2, 0, 5])

In [26]:
# .reduce between columns
display(np.minimum.reduce(C, axis=1))   # minimum in each col of the 3 rows
display(np.min(C, axis=1))

array([0, 3, 3])

array([0, 3, 3])

Statistics - Order statistics

ptp(a[, axis, out, keepdims])
Range of values (maximum - minimum) along an axis.

percentile(a, q[, axis, out, ...])
Compute the q-th percentile of the data along the specified axis.

nanpercentile(a, q[, axis, out, ...])
Compute the qth percentile of the data along the specified axis, while ignoring nan values.

quantile(a, q[, axis, out, overwrite_input, ...])
Compute the q-th quantile of the data along the specified axis.

nanquantile(a, q[, axis, out, ...])
Compute the qth quantile of the data along the specified axis, while ignoring nan values.