# 7 Statistics with NumPy
## 7_5A Exercises

#### numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)

#### numpy.average(a, axis=None, weights=None, returned=False, *, keepdims=<no value>)

#### numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

#### numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>, mean=<no value>, correction=<no value>)

#### numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>, mean=<no value>, correction=<no value>)

#### numpy.cov(m, y=None, rowvar=True, bias=False, ddof=None, fweights=None, aweights=None, *, dtype=None)

#### numpy.corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>, *, dtype=None)

In [2]:
import numpy as np
np.__version__

'1.26.4'

In [3]:
# Functions

def show_attr(arrnm: str) -> str:
    strout = f' {arrnm}: '

    for attr in ('shape', 'ndim', 'size', 'dtype'):     #, 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

In [4]:
A = np.array([[1,0,0,3,1],
              [3,6,6,2,9],
              [4,5,3,8,0]])

print(show_attr('A'))
A

 A: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 


array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

#### 1. What does the main diagonal of the matrix returned by np.cov() represent when calculating the covariance of a 2D array?
- Te variance of each row in the array
- The main diagonal elements of the covariance matrix represent the variance of each row, as the covariance between an element and itself is simply its variance.

In [5]:
# FUTURE: investigate de formulas - NOT the same numbers
print(f'{np.var(A[0])}  -  {np.var(A[1])}  -  {np.var(A[2])}')
display(np.var(A, axis=1))
display(np.cov(A[0], A[1]))
np.cov(A)

1.2  -  6.160000000000001  -  6.8


array([1.2 , 6.16, 6.8 ])

array([[ 1.5, -2. ],
       [-2. ,  7.7]])

array([[ 1.5, -2. ,  2. ],
       [-2. ,  7.7, -7. ],
       [ 2. , -7. ,  8.5]])

In [6]:
# Covariance of Columns
display(np.cov(A[:,0], A[:,1]))
display(np.cov(A[:,0], A[:,2]))
display(np.cov(A[:,1], A[:,2]))

array([[ 2.33333333,  4.33333333],
       [ 4.33333333, 10.33333333]])

array([[2.33333333, 3.        ],
       [3.        , 9.        ]])

array([[10.33333333,  9.        ],
       [ 9.        ,  9.        ]])

In [15]:
# cov(X, X) = var(X)
d1= np.arange(50)
np.cov(d1, d1)
np.var(d1)

208.25

#### 2. Match
- Computes the arithmetic average of a dataset. -> np.mean(), np.average()
- Computes the covariance between rows of a 2D array. -> np.cov(2D-array)
- Returns the middle value of a sorted dataset -> np.median() | the value in the middle position of a sorted (in ascending order) dataset.
- Calculates the variance of the dataset. -> np.var()
- Computes the correlation coefficients between rows of a 2D array. -> np.corrcoef(2D-array)
- Computes the standard deviation of the dataset. -> np.std()

Correlating

corrcoef(x[, y, rowvar, bias, ddof, dtype])
Return Pearson product-moment correlation coefficients.

correlate(a, v[, mode])
Cross-correlation of two 1-dimensional sequences.

cov(m[, y, rowvar, bias, ddof, fweights, ...])
Estimate a covariance matrix, given data and weights.