# Statistsics w/ NumPy

### 1. Run the following cells:

In [2]:
import numpy as np
np.__version__

'1.26.4'

In [3]:
np.set_printoptions(suppress = True, linewidth = 150, precision = 2)

In [4]:
array_1D = np.array([10,11,12,13,14])
array_1D

array([10, 11, 12, 13, 14])

In [5]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [33]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
print(array_3D.shape, array_3D.ndim)
array_3D

(2, 2, 5) 3


array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 2. For each of the 3 arrays we defined above, do the following:
    A) Call the np.max() or np.amax() function and plug in the array as an input. 
    B) Call the np.max() or np.amax() function along an axis of your choice and plug in the array as an input.
    C) Call the np.maximum.reduce() function and plug in the array as an input. 


In [7]:
np.max(array_1D)

14

In [8]:
np.max(array_2D)

87

In [9]:
np.max(array_3D)

54

In [10]:
np.max(array_1D, axis=0)    # the row (only axis here)

14

In [19]:
display(np.max(array_2D, axis=0))    # the columns (last axis)
display(np.max(array_2D, axis=1))    # the rows (first axis)

array([43, 54, 65, 76, 87])

array([60, 87, 55])

In [35]:
display(array_3D)
display(np.max(array_3D, axis=0))    # the deep axis () - result 2x5
display(np.max(array_3D, axis=1))    # the columns axis - result 2x5
display(np.max(array_3D, axis=2))    # the files axis   - result 2x2

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

array([[11, 12, 13, 14, 15],
       [51, 52, 53, 54, 51]])

array([[11, 21, 31, 41, 51],
       [51, 52, 53, 54, 15]])

array([[ 5, 51],
       [15, 54]])

In [14]:
np.maximum.reduce(array_1D)     # Only one axis, ergo same as np.max()

14

In [20]:
display(np.maximum.reduce(array_2D))    # same as np.max(A, axis=0) -> last axis (cols)
display(np.maximum.reduce(array_2D, axis=0))    # same as np.max(A, axis=0) -> last axis (cols)
display(np.maximum.reduce(array_2D, axis=1))    # same as np.max(A, axis=1) -> first (rows)

array([43, 54, 65, 76, 87])

array([43, 54, 65, 76, 87])

array([60, 87, 55])

In [21]:
np.maximum.reduce(array_3D)     # deppt axis
# axis=0, =1, =2 idem 

array([[11, 12, 13, 14, 15],
       [51, 52, 53, 54, 51]])

In [25]:
# JM: maximun (maxima <- plural) of two arrays same shape
display(array_2D[:2], array_3D[1])
np.maximum(array_2D[:2], array_3D[1])

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87]])

array([[11, 12, 13, 14, 15],
       [51, 52, 53, 54,  5]])

array([[20, 30, 40, 50, 60],
       [51, 54, 65, 76, 87]])

### 3. For each array find the difference between its maximum and minimum. 
   <b>Note:</b> Use the <i>np.ptp() </i> function

In [26]:
np.ptp(array_1D)

4

In [27]:
np.ptp(array_2D)

76

In [28]:
np.ptp(array_3D)

53

### 4. For the 2-D and 3-D arrays find the difference between the maximum and minimum, for every row.

In [30]:
display(array_2D)
np.ptp(array_2D, axis=1)

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

array([40, 44, 44])

In [32]:
display(array_3D)
np.ptp(array_3D, axis=2)

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

array([[ 4, 40],
       [ 4, 49]])

### 5. For all 3 arrays we defined, use the<i> np.percentile() </i>and <i>np.quantile()</i> functions to find the following: 
    A) The 30-th percentile (or 0.3-th quantile). 
    B) The 66-th percentile (or 0.66-th qunatile). 
    C) The median. 
   (<b>Hint</b>: The median value is equivalent to the 50-th percentile)

#### 1D array:

In [36]:
np.sort(array_1D)

# We're also providing a sorted version of the inputs, so that the outputs are more easy to understand.

array([10, 11, 12, 13, 14])

In [41]:
display(np.percentile(array_1D, 30, interpolation='nearest'))
display(np.quantile(array_1D, 0.3, interpolation='nearest'))

11

11

In [42]:
display(np.percentile(array_1D, 66, interpolation='nearest'))
display(np.quantile(array_1D, 0.66, interpolation='nearest'))

13

13

In [43]:
display(np.percentile(array_1D, 50, interpolation='nearest'))
display(np.quantile(array_1D, 0.50, interpolation='nearest'))
np.median(array_1D)

12

12

12.0

#### 2D array:

In [44]:
np.sort(array_2D, axis = None)

# We're also providing a sorted version of the inputs, so that the outputs are more easy to understand.

array([11, 20, 22, 30, 33, 40, 43, 44, 50, 54, 55, 60, 65, 76, 87])

In [45]:
display(np.percentile(array_2D, 30, interpolation='nearest'))
display(np.quantile(array_2D, 0.3, interpolation='nearest'))

33

33

In [47]:
display(np.percentile(array_2D, 66, interpolation='nearest'))
display(np.quantile(array_2D, 0.66, interpolation='nearest'))

54

54

In [48]:
display(np.percentile(array_2D, 56, interpolation='nearest'))
display(np.quantile(array_2D, 0.50, interpolation='nearest'))
np.median(array_2D)

50

44

44.0

#### 3D array

In [49]:
np.sort(array_3D, axis = None)

# We're also providing a sorted version of the inputs, so that the outputs are more easy to understand.

array([ 1,  2,  3,  4,  5,  5, 11, 11, 12, 13, 14, 15, 21, 31, 41, 51, 51, 52, 53, 54])

In [ ]:
# JM function
def per_quan_med ()

### 6. For the 3 arrays:
    A) Find the mean.
    B) Find the median.
    C) Find the mean along the columns.

#### 1D array:

#### 2D array:

#### 3D array:

### 7. For the 2D array:
    A) Find the variance. 
    B) Find the standard deviation. 
    C) Find the covariance. 
    D) Find the correlation. 

### 8. For the 2D array:
    A) Find the "default "bin edges for a histogram (don't specify any arguments)
    B) Set the number of bins to 6
    C) Define a range
    D) With the help of the matplotlib package, plot the 3 histograms

### 9. For the 3-D array:
    A) Take the first two rows, and compute their 2-D histogram, with 4 bins    .
    B) Take the entire 2-D array and find its 3-D histogram with 4 bins. 
   (<b>Hint</b>: You'll need to plug in the <b>transpose</b> for B to work) 
   

### 10. Run the following cell, and then compute the following:
    A) The mean, using the np.mean() function.
    B) The mean, using the np.nanmean() function.
    C) The variance, using the np.var() function. 
    D) The variance, using the np.nanvar() funcion. 

In [ ]:
array_nan = np.array([[20,np.nan,40,50,60], [np.nan,54,65,np.nan,87], [11,22,33,44,np.nan]])
array_nan