# 8 Data Manipulation with NumPy
- Examine how to clean and preprocess data using NumPy.
- Hoy to discover missing values (and fill them up).
- Ways to remove irrelevant data.
- sort(), shuffle(), reshape(), stack(), strip()
## 8_09 Assigning Types - Casting - Type Casting

#### ndarray.astype(dtype, order='K', casting='unsafe', subok=True, copy=True) <- method
- Copy of the array, cast to a specified type.

#### Type Casting (Casting)
- Create a new identical objet with all values of diff. type
- float -> int, int -> float, str -> float -> int, etc.

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
# Function show_attr

def show_attr(arrnm: str) -> str:
    strout = f' {arrnm}: '

    for attr in ('shape', 'ndim', 'size', 'dtype'):     #, 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

In [3]:
# To see more clear we´ll use only a part of the dataset

lend_co_num = np.loadtxt('Lending-Company-Numeric-Data.csv',
                           delimiter=',')

display(show_attr('lend_co_num'))
lend_co_num

' lend_co_num: | shape: (1043, 6) | ndim: 2 | size: 6258 | dtype: float64 '

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [4]:
# convert to np.int32 - # inplace > false, unless copy=
display(lend_int :=lend_co_num.astype(dtype=np.int32))
show_attr('lend_int')

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]])

' lend_int: | shape: (1043, 6) | ndim: 2 | size: 6258 | dtype: int32 '

In [5]:
# convert to str - # inplace > false, unless copy=
display(lend_str :=lend_co_num.astype(dtype=str))
show_attr('lend_str')

array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

' lend_str: | shape: (1043, 6) | ndim: 2 | size: 6258 | dtype: <U32 '

In [6]:
# str -> int, usually problems with decimal point if exists
# lend_str.astype(np.int32)   # ValueError: invalid literal for int() with base 10: '2000.0'
# Then, str -> float -> int
display(l_int2 := lend_str.astype(np.float32).astype(np.int32))
show_attr('l_int2')

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]])

' l_int2: | shape: (1043, 6) | ndim: 2 | size: 6258 | dtype: int32 '

### Notes and Exmples from Manual - ndarray.astype
- Changed in version 1.17.0: Casting between a simple data type and a structured one is possible only for “unsafe” casting. Casting to multiple fields is allowed, but casting from multiple fields is not.
- Changed in version 1.9.0: Casting from numeric to string types in ‘safe’ casting mode requires that the string dtype length is long enough to store the max integer/float value converted.