# 8 Data Manipulation with NumPy
- Examine how to clean and preprocess data using NumPy.
- Hoy to discover missing values (and fill them up).
- Ways to remove irrelevant data.
- sort(), shuffle(), reshape(), stack(), strip()
## 8_14A Exercises

- np.loadtxt() | fails with missing vals (NANs)
- np.isnan() |  np.isnan().sum()
- np.genfromtxt(filling_values=temp_fill)
- np.where(condition, True, False)
- np.reshape() | add dims artificially -> np.reshape(1,1,3,5) <- inplace False
- np.delete(var, els) | (var, els, axis=0) row, (var, els, axis=1) cols | delete(delete, axis=1) axis=0) cols and rows <-inplace False
- np.sort() | -np.sort(-arr) <- inplace False | arr.sort() <- inplace True!! | axis=-1 default (en 2D is = 1 rows)
- np.argsort()

In [18]:
import numpy as np
np.__version__

'1.26.4'

### 1. When using the np.sum() function on a boolean array returned by np.isnan(), the result will indicate the total number of missing values in the dataset.
- True
- Explanation: In NumPy, True can be represented with 1 and False can be represented with 0. Summing the boolean array returned by np.isnan() will count the number of True values, which corresponds to the number of missing values.

### 2. Filling missing values with the mean of the column will not change the overall mean of that column.
- True
- Explanation: Filling missing values with the mean of a column ensures that the overall mean remains unchanged. This method keeps the distribution of data consistent while handling missing values.

### 3. What does the np.where() function do?
- It replaces values in an array based on a condition.

### 4. Setting axis=None in np.sort() on a 2D array will sort the flattened array and return a 1D array.
- True 

### 5. Which of the following best describes the default behavior of np.sort() when sorting a 2D array?
- It sorts each row of the array in ascending order.
- Explanation: The default behavior of np.sort() on a 2D array is to sort each row (the last axis) individually in ascending order.

## Some JM - Exercises

In [20]:
display(A := np.arange(1,7).reshape(2,3))
np.reshape(A, (3,2))    # <- Inplace=False
display(A)
A.reshape(3,2)          # <- Inplace=False
B = A.reshape(3,2) 
B

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
display(C := np.arange(6,0,-1).reshape(2,3))
display(np.sort(C))
display(np.sort(C, axis=1))
display(np.sort(C, axis=-1))    # sort rows
C
display(np.sort(C, axis=0))     # sort cols
C
display(C.sort())
C

array([[6, 5, 4],
       [3, 2, 1]])

array([[4, 5, 6],
       [1, 2, 3]])

array([[4, 5, 6],
       [1, 2, 3]])

array([[4, 5, 6],
       [1, 2, 3]])

array([[3, 2, 1],
       [6, 5, 4]])

None

array([[4, 5, 6],
       [1, 2, 3]])

In [28]:
# sorting in descending order
display(np.flip(np.sort(C)))
display(C)
-np.sort(-C)
C

array([[3, 2, 1],
       [6, 5, 4]])

array([[4, 5, 6],
       [1, 2, 3]])

array([[4, 5, 6],
       [1, 2, 3]])

In [35]:
# Sorting letters in descending orged
lst = [chr(i) for i in range(100, 115)]
display(L := np.array(lst).reshape(3,5))
display(np.sort(L))
np.flip(np.sort(L))
# numpy.flip(m, axis=None)

array([['d', 'e', 'f', 'g', 'h'],
       ['i', 'j', 'k', 'l', 'm'],
       ['n', 'o', 'p', 'q', 'r']], dtype='<U1')

array([['d', 'e', 'f', 'g', 'h'],
       ['i', 'j', 'k', 'l', 'm'],
       ['n', 'o', 'p', 'q', 'r']], dtype='<U1')

array([['r', 'q', 'p', 'o', 'n'],
       ['m', 'l', 'k', 'j', 'i'],
       ['h', 'g', 'f', 'e', 'd']], dtype='<U1')