# 8 Data Manipulation with NumPy
- Examine how to clean and preprocess data using NumPy.
- Hoy to discover missing values (and fill them up).
- Ways to remove irrelevant data.
- sort(), shuffle(), reshape(), stack(), strip()
## 8_14A Exercises

- np.loadtxt() | fails with missing vals (NANs)
- np.isnan() |  np.isnan().sum()
- np.genfromtxt(filling_values=temp_fill)
- np.where(condition, True, False)
- np.reshape() | add dims artificially -> np.reshape(1,1,3,5) <- inplace False
- np.delete(var, els) | (var, els, axis=0) row, (var, els, axis=1) cols | delete(delete, axis=1) axis=0 cols and rows <-inplace False
- np.sort() | -np.sort(-arr) <- inplace False | arr.sort() <- inplace True!! | axis=-1 default (en 2D is = 1 rows)
- np.argsort() | def axis=-1 | .argsort() method idem <- inplacer False>
- np.argwhere(a) | indices of non-zero elements of a
- np.shuffle() | <-inplace TRUE> NO axis= | Also .shuffle() Generator method <-inplace True> axis=0 rows default - 2-D array axis=0 shuffle rows, axis=1 shuffle cols.
- np.astype() | <- inplace False> idem the .astype() method
- np.chararray.strip() | <- inplacer False>
- np.stack() | def. axis=0 build rows == .vstack(), axis=1 == .hstack() | .stack() SAME shape, .vstack() and .hstack() NO  | .dstack() depth


In [140]:
import numpy as np
np.__version__

'1.26.4'

### 1. When using the np.sum() function on a boolean array returned by np.isnan(), the result will indicate the total number of missing values in the dataset.
- True
- Explanation: In NumPy, True can be represented with 1 and False can be represented with 0. Summing the boolean array returned by np.isnan() will count the number of True values, which corresponds to the number of missing values.

### 2. Filling missing values with the mean of the column will not change the overall mean of that column.
- True
- Explanation: Filling missing values with the mean of a column ensures that the overall mean remains unchanged. This method keeps the distribution of data consistent while handling missing values.

### 3. What does the np.where() function do?
- It replaces values in an array based on a condition.

### 4. Setting axis=None in np.sort() on a 2D array will sort the flattened array and return a 1D array.
- True 

### 5. Which of the following best describes the default behavior of np.sort() when sorting a 2D array?
- It sorts each row of the array in ascending order.
- Explanation: The default behavior of np.sort() on a 2D array is to sort each row (the last axis) individually in ascending order.

### 6. The np.argwhere() function returns the coordinates of all non-zero elements in a NumPy array by
- True
- Explanation: By default, np.argwhere() checks for non-zero elements in the array and returns their coordinates as indices in a 2D array.

### 7. When using np.random.shuffle() the function returns a new array without modifying the original array.
- False
- Explanation: np.random.shuffle() modifies the array in place, meaning it rearranges the rows of the dataset directly and does not return a new array.

### 8. You have a 2D array of float values and you want to cast them into integers. Complete the following code:


In [141]:
data = np.array([[1.2, 2.5, 3.1], [4.6, 5.8, 6.9]]) 

# Convert float values to integers
int_data = data.astype(dtype = np.int32) 
print(int_data)

[[1 2 3]
 [4 5 6]]


## Some JM - Exercises

In [142]:
display(A := np.arange(1,7).reshape(2,3))
np.reshape(A, (3,2))    # <- Inplace=False
display(A)
A.reshape(3,2)          # <- Inplace=False
B = A.reshape(3,2) 
B

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [143]:
display(C := np.arange(6,0,-1).reshape(2,3))
display(np.sort(C))
display(np.sort(C, axis=1))
display(np.sort(C, axis=-1))    # sort rows
C
display(np.sort(C, axis=0))     # sort cols
C
display(C.sort())
C

array([[6, 5, 4],
       [3, 2, 1]])

array([[4, 5, 6],
       [1, 2, 3]])

array([[4, 5, 6],
       [1, 2, 3]])

array([[4, 5, 6],
       [1, 2, 3]])

array([[3, 2, 1],
       [6, 5, 4]])

None

array([[4, 5, 6],
       [1, 2, 3]])

In [144]:
# sorting in descending order
display(np.flip(np.sort(C)))
display(C)
-np.sort(-C)
C

array([[3, 2, 1],
       [6, 5, 4]])

array([[4, 5, 6],
       [1, 2, 3]])

array([[4, 5, 6],
       [1, 2, 3]])

In [145]:
# Sorting letters in descending orged
lst = [chr(i) for i in range(100, 115)]
display(L := np.array(lst).reshape(3,5))
display(np.sort(L))
np.flip(np.sort(L))
# numpy.flip(m, axis=None)

array([['d', 'e', 'f', 'g', 'h'],
       ['i', 'j', 'k', 'l', 'm'],
       ['n', 'o', 'p', 'q', 'r']], dtype='<U1')

array([['d', 'e', 'f', 'g', 'h'],
       ['i', 'j', 'k', 'l', 'm'],
       ['n', 'o', 'p', 'q', 'r']], dtype='<U1')

array([['r', 'q', 'p', 'o', 'n'],
       ['m', 'l', 'k', 'j', 'i'],
       ['h', 'g', 'f', 'e', 'd']], dtype='<U1')

In [146]:
display(L)
L[0,3] = '' 
L[1,1] = 0
L[2,4] = False
display(L)
display(L[L == True])
display(L[L == False])

array([['d', 'e', 'f', 'g', 'h'],
       ['i', 'j', 'k', 'l', 'm'],
       ['n', 'o', 'p', 'q', 'r']], dtype='<U1')

array([['d', 'e', 'f', '', 'h'],
       ['i', '0', 'k', 'l', 'm'],
       ['n', 'o', 'p', 'q', 'F']], dtype='<U1')

array([], dtype='<U1')

array([], dtype='<U1')

In [147]:
display(R := np.random.randn(15).round(2).reshape(3,5) * 17)
R[0,3] = R[1,0] = R[2,4] = 0
display(R)
display(R[R == True])
display(R[R == False])
display(R[R != False])
display(R[R != True])

array([[  1.19,  21.76, -24.99,   3.74,  15.64],
       [ 12.24, -10.88,  28.56,   8.16,  25.16],
       [-12.92,   2.72,  20.06,   1.53,   3.74]])

array([[  1.19,  21.76, -24.99,   0.  ,  15.64],
       [  0.  , -10.88,  28.56,   8.16,  25.16],
       [-12.92,   2.72,  20.06,   1.53,   0.  ]])

array([], dtype=float64)

array([0., 0., 0.])

array([  1.19,  21.76, -24.99,  15.64, -10.88,  28.56,   8.16,  25.16,
       -12.92,   2.72,  20.06,   1.53])

array([  1.19,  21.76, -24.99,   0.  ,  15.64,   0.  , -10.88,  28.56,
         8.16,  25.16, -12.92,   2.72,  20.06,   1.53,   0.  ])

In [148]:
# .shuffle Gen method, inplace True, axis=0 rows default
display(I := np.arange(18).reshape(3,6))

from numpy.random import Generator as gen  
from numpy.random import PCG64 as pcg 

array_RG = gen(pcg())
array_RG.shuffle(I, axis=0)

I


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

array([[12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [149]:
# display(I := np.arange(18).reshape(3,6))
# np.random.shuffle(I, axis=1)
# I
# # TypeError: shuffle() got an unexpected keyword argument 'axis'

In [150]:
# .astype() method <- inplace False
display(I := np.arange(18).reshape(3,6))
display(I)
display(I.astype(dtype=str))
display(I)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

array([['0', '1', '2', '3', '4', '5'],
       ['6', '7', '8', '9', '10', '11'],
       ['12', '13', '14', '15', '16', '17']], dtype='<U11')

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [151]:
## The truth about the 'same' shape in stacks
display(S := np.arange(24).reshape(4,6))
display(S2r := S[[-1,-2]])
# np.stack((S,S2r) # ValueError: all input arrays must have the same shape

np.vstack((S,S2r))  # OK!!

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

array([[18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17]])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17]])