# Appendix 1 - Functions

[## 0. Import Libraries](#0-import-libraries)    
[## 1. show_attr function](#1-show_attr-function)    
[## 2. show_thsep function](#2-show_thsep-function)    
[## 3. show_tharrsep function](#3-show_tharrsep-function)

## 0. Import Libraries

In [27]:
import numpy as np
np.__version__
np.set_printoptions(suppress=True, linewidth=100)
# np.set_printoptions(suppress=True, linewidth=100, precision=2)

import numpy

In [28]:
# Create some test arrays
int_arange = np.arange(15).reshape(3,5)
float_rand = np.round(np.random.random(size=(3,5)) * 500_000, 2)
int_rand = np.random.randint(10, 40, size=(3,5))
float_arange = np.arange(10000, 10045, 3, dtype=np.float32).reshape(3,5)

arr_1D = float_rand[1]
arr_3D = np.array([float_arange, float_rand])

# display(int_arange, float_rand, int_rand, float_arange, arr_1D, arr_3D)


## 1. show_attr function

[# Appendix 1 - Functions](#appendix-1---functions)

In [29]:
# Function show_attr def

def show_attr(arrnm: str) -> str:
    ''' Show numpy ndarray principal attributes
    
    arrnm: array name. Must exist en the main program body
    --> CAN NOT be call inside other function
    '''
    
    if not isinstance(arrnm, str):
          return '-> show_attr() >> ERROR: argument must be an string!'
    
    strout = f' {arrnm}: '
    for attr in ('shape', 'ndim', 'size', 'dtype'):     #, 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

In [30]:
# show_attr test
display(show_attr('int_rand'))
# display(show_attr(int_rand))    # '--> show_attr() >> ERROR: argument must be an string!'
# show_attr?

' int_rand: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 '

In [31]:
# Shapes and attributes
# display(arr_1D, show_attr('arr_1D'))
# display(arr_1D)
# arr_1D = np.reshape(arr_1D, (5,1))
# display(arr_1D, show_attr('arr_1D'))

## 2. show_thsep function

[# Appendix 1 - Functions](#appendix-1---functions)

In [32]:
# Function show_thsep

def show_thsep(num: float, sep: str = ',') -> str:
    '''Show num as str with thousands separator
    
    num: a real number (int or float)
    sep: separator, valid are: ';', '_', or ':'
    '''

    if not (isinstance(num, int) or isinstance(num, float) or
        isinstance(num, np.number)):
        return f'-> show_thsep() >> ERROR: argument must be \
a number not a {type(num)}'
    
    if not (sep == ',' or sep == '_'):
        return "-> show_thsep() >> ERROR: sep must be ',' or '_'"

    n_str = str(num)
    dec_ix = n_str.find('.')        # decimal sep index
    if dec_ix > -1:                 # dec_part exist
        dec_part = n_str[dec_ix:]
        int_pr = n_str[:dec_ix][::-1]
    else:                           # there's no dec_part
        dec_part = ''
        int_pr = n_str[::-1]

    int_part = ''
    for dig in range(len(int_pr)):  # for e/digit in int_pr
        int_part += int_pr[dig]
        # every 3 dig add sep but not for the last (1st not-reversed)
        if (dig + 1) % 3 == 0 and dig != (len(int_pr) - 1):
            int_part += sep
    
    return int_part[::-1] + dec_part

In [33]:
# # show_thsep test
display(n := '98723948759.34354')
display(show_thsep(n))         # '-> show_thseps() >> ERROR: argument must be a number (int or float)'

display(n := 98723948759.34354)
display(show_thsep(n, '|'))    # "-> show_thseps() >> ERROR: sep must be ';', '_', or ':'"

display(show_thsep(None))

display(n := 98723948759.34354)
display(show_thsep(n))

display(n := 5)
display(show_thsep(n))    

display(n := 47.825)
display(show_thsep(n))   

display(n := 00.4512)
display(show_thsep(n))   

display(n := 250327.63)
display(show_thsep(n))    

'98723948759.34354'

"-> show_thsep() >> ERROR: argument must be a number not a <class 'str'>"

98723948759.34354

"-> show_thsep() >> ERROR: sep must be ',' or '_'"

"-> show_thsep() >> ERROR: argument must be a number not a <class 'NoneType'>"

98723948759.34354

'98,723,948,759.34354'

5

'5'

47.825

'47.825'

0.4512

'0.4512'

250327.63

'250,327.63'

## 3. show_tharrsep function

[# Appendix 1 - Functions](#appendix-1---functions)

In [38]:
# function show_tharrsep()

def show_tharrsep(arr: np.ndarray, sep: str = '_') -> np.ndarray[str]:
    '''Show numeric elements as str with thousands
    separator within a numpy array
    
    arr: numpy ndarray genuine dims valid: [0,1,2,3]
    sep: separator, valid are: ',' or '_' (default)
    '''
    if not isinstance(arr, np.ndarray):
        return "-> show_tharrsep >> ERROR: not an np.ndarray"
    
    arr = arr.squeeze()     # for cases w/artificial dims
    if arr.ndim == 0:
        arr = np.reshape(arr, (1, 1, 1))
    elif arr.ndim == 1:
        arr = np.reshape(arr, (1, 1, arr.shape[0]))
    elif arr.ndim == 2:
        arr = np.reshape(arr, (1, arr.shape[0], arr.shape[1]))
    elif arr.ndim > 3:
        print("-> show_tharrsep >> ERROR: array ndim out of range")

    ret_arr = np.ones_like(arr, dtype='>U32')
    for tbl in range(arr.shape[0]):
        for row in range(arr.shape[1]):
            for col in range(arr.shape[2]):
                ret_arr[tbl, row, col] = show_thsep(arr[tbl, row, col],
                                                    sep=sep)

    return ret_arr.squeeze()

In [45]:
arr_pru = np.arange(100000, 100050, 5, dtype=float).reshape(2,5)
display(arr_pru)
show_tharrsep(arr_pru)

array([[100000., 100005., 100010., 100015., 100020.],
       [100025., 100030., 100035., 100040., 100045.]])

array([['100_000.0', '100_005.0', '100_010.0', '100_015.0', '100_020.0'],
       ['100_025.0', '100_030.0', '100_035.0', '100_040.0', '100_045.0']], dtype='>U32')

In [10]:
display(show_tharrsep(float_rand))
display(show_tharrsep(arr_1D))
display(show_tharrsep(arr_3D))
display(show_tharrsep(float_rand[0], sep=','))
display(show_tharrsep(np.array([[[[[587663.787]]]]])))
display(show_thsep(587663.787))

 arr: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 
[[146887.45 325833.55  16481.09  15829.93 137216.28]
 [499492.71  41396.75 147143.8  480230.31  69520.32]
 [194107.34 428099.34 399273.89 381830.86  18694.72]]
[[[146887.45 325833.55  16481.09]
  [ 15829.93 137216.28 499492.71]
  [ 41396.75 147143.8  480230.31]
  [ 69520.32 194107.34 428099.34]
  [399273.89 381830.86  18694.72]]]
 arr: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 


array([['146_887.45', '325_833.55', '16_481.09'],
       ['15_829.93', '137_216.28', '499_492.71'],
       ['41_396.75', '147_143.8', '480_230.31'],
       ['69_520.32', '194_107.34', '428_099.34'],
       ['399_273.89', '381_830.86', '18_694.72']], dtype='>U32')

 arr: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 
 arr: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 


array(['499_492.71', '41_396.75', '147_143.8', '480_230.31', '69_520.32'], dtype='>U32')

 arr: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 
 arr: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 


array([[['10_000.0', '10_003.0', '10_006.0', '10_009.0', '10_012.0'],
        ['10_015.0', '10_018.0', '10_021.0', '10_024.0', '10_027.0'],
        ['10_030.0', '10_033.0', '10_036.0', '10_039.0', '10_042.0']],

       [['146_887.45', '325_833.55', '16_481.09', '15_829.93', '137_216.28'],
        ['499_492.71', '41_396.75', '147_143.8', '480_230.31', '69_520.32'],
        ['194_107.34', '428_099.34', '399_273.89', '381_830.86', '18_694.72']]], dtype='>U32')

 arr: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 
 arr: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 


array(['146,887.45', '325,833.55', '16,481.09', '15,829.93', '137,216.28'], dtype='>U32')

 arr: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 
 arr: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 


array('587_663.787', dtype='>U32')

'587,663.787'