# Appendix 1 - Functions
## TO-DO: fix show_thsep when justo 100_000 o mult de 3.
#### tal vez poner el adicionar el digito debajo de comp % 3

[## 0. Import Libraries](#0-import-libraries)    
[## 1. show_attr function](#1-show_attr-function)    
[## 2. show_thsep function](#2-show_thsep-function)    
[## 3. show_tharrsep function](#3-show_tharrsep-function)

## 0. Import Libraries

In [1]:
import numpy as np
np.__version__
np.set_printoptions(suppress=True, linewidth=100)
# np.set_printoptions(suppress=True, linewidth=100, precision=2)

In [2]:
# Create some test arrays
int_arange = np.arange(15).reshape(3,5)
float_rand = np.round(np.random.random(size=(3,5)) * 500_000, 2)
int_rand = np.random.randint(10, 40, size=(3,5))
float_arange = np.arange(10000, 10045, 3, dtype=np.float32).reshape(3,5)

display(int_arange, float_rand, int_rand, float_arange)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[291380.18,   7380.07, 426044.21, 480428.79, 483444.54],
       [ 86217.92, 240694.96, 391659.13, 303886.12, 113330.31],
       [  3262.97, 305969.78, 365716.1 , 381143.4 ,  19269.14]])

array([[10, 22, 11, 14, 13],
       [16, 39, 25, 14, 10],
       [33, 37, 23, 34, 16]])

array([[10000., 10003., 10006., 10009., 10012.],
       [10015., 10018., 10021., 10024., 10027.],
       [10030., 10033., 10036., 10039., 10042.]], dtype=float32)

## 1. show_attr function

In [3]:
# Function show_attr def

def show_attr(arrnm: str) -> str:
    if not isinstance(arrnm, str):
          return '-> show_attr() >> ERROR: argument must be an string!'
    
    strout = f' {arrnm}: '
    for attr in ('shape', 'ndim', 'size', 'dtype'):     #, 'itemsize'):
            arrnm_attr = arrnm + '.' + attr
            strout += f'| {attr}: {eval(arrnm_attr)} '

    return strout

In [4]:
# show_attr test
display(show_attr('int_rand'))
# display(show_attr(int_rand))    # '--> show_attr() >> ERROR: argument must be an string!'
# show_attr?

' int_rand: | shape: (3, 5) | ndim: 2 | size: 15 | dtype: int32 '

## 2. show_thsep function

In [5]:
# Function show_thsep

def show_thsep(num: float, sep: str = ',') -> str:
    '''Insert thousands separator
    
    num: a real number (int or float)
    sep: separator, valid are: ';', '_', or ':'
    '''

    if (isinstance(num, str) or isinstance(num, bool)):
        return '-> show_thsep() >> ERROR: argument must be a number'
    
    if not (sep == ',' or sep == '_' or sep == ':'):
        return "-> show_thsep() >> ERROR: sep must be ';', '_', or ':'"

    n_str = str(num)
    dec_ix = n_str.find('.')        # decimal sep index
    if dec_ix > -1:                 # dec_part exist
        dec_part = n_str[dec_ix:]
    else:
        dec_ix = len(n_str)         # there's no dec_part
        dec_part = ''

    int_pr = n_str[:dec_ix][::-1]   # integer part reverser
    int_part = ''
    for dig in range(len(int_pr)):  # for e/digit in int_pr
        int_part += int_pr[dig]
        if (dig + 1) % 3 == 0:     # every 3 dig add sep
            int_part += sep
    
    return int_part[::-1] + dec_part    
        

In [6]:
# show_thsep test
display(n := '98723948759.34354')
display(show_thsep(n))         # '-> show_thseps() >> ERROR: argument must be a number (int or float)'

display(n := 98723948759.34354)
display(show_thsep(n, '|'))    # "-> show_thseps() >> ERROR: sep must be ';', '_', or ':'"

display(n := 98723948759.34354)
display(show_thsep(n))

display(n := 5)
display(show_thsep(n))    

'98723948759.34354'

'-> show_thsep() >> ERROR: argument must be a number'

98723948759.34354

"-> show_thsep() >> ERROR: sep must be ';', '_', or ':'"

98723948759.34354

'98,723,948,759.34354'

5

'5'

In [ ]:
# Let's try show_thsep for an array
display(int_arange)

arr = float_arange
ixs = arr.shape

display(ret_arr := np.ones_like(arr, dtype='>U32'))
for row in range(arr.shape[0]):
    for col in range(arr.shape[1]):
        # print(arr[row, col], type(arr[row, col]), show_thsep(arr[row, col]))
        ret_arr[row, col] = show_thsep(arr[row, col])

ret_arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='>U32')

array([['10,000.0', '10,003.0', '10,006.0', '10,009.0', '10,012.0'],
       ['10,015.0', '10,018.0', '10,021.0', '10,024.0', '10,027.0'],
       ['10,030.0', '10,033.0', '10,036.0', '10,039.0', '10,042.0']], dtype='>U32')

## 3. show_tharrsep function

In [8]:
def show_tharrsep(arr: np.ndarray, sep: str = '_'):
    if not isinstance(arr, np.ndarray):
        return "-> show_tharrsep >> ERROR: not an np.ndarray"
    
    ret_arr = np.ones_like(arr, dtype='>U32')
    for row in range(arr.shape[0]):
        for col in range(arr.shape[1]):
            ret_arr[row, col] = show_thsep(arr[row, col], sep=sep)

    return ret_arr

In [9]:
display(float_rand)
show_tharrsep(float_rand)

array([[291380.18,   7380.07, 426044.21, 480428.79, 483444.54],
       [ 86217.92, 240694.96, 391659.13, 303886.12, 113330.31],
       [  3262.97, 305969.78, 365716.1 , 381143.4 ,  19269.14]])

array([['_291_380.18', '7_380.07', '_426_044.21', '_480_428.79', '_483_444.54'],
       ['86_217.92', '_240_694.96', '_391_659.13', '_303_886.12', '_113_330.31'],
       ['3_262.97', '_305_969.78', '_365_716.1', '_381_143.4', '19_269.14']], dtype='>U32')

In [10]:
# ret_arr

# def show_tharrsep(arr):
#     if arr.dtype == str:
#         return '-> show_tharrsep() >> ERROR: ndarray.dtype = str'
    
#     ixs = arr.shape
#     ret_arr = np.ones_like(arr)
#     for row in range(arr.shape[0]):
#         for col in range(arr.shape[1]):